// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options as ClientOptions,
  type TDataShape,
  type Client,
  formDataBodySerializer,
  urlSearchParamsBodySerializer,
} from './client'
import type {
  ListTenantsTenantsGetData,
  ListTenantsTenantsGetResponses,
  RemoveTenantTenantsTenantIdDeleteData,
  RemoveTenantTenantsTenantIdDeleteResponses,
  LerAtendimentosData,
  LerAtendimentosResponses,
  LerAtendimentosErrors,
  CriarAtendimentosData,
  CriarAtendimentosResponses,
  ProcessarAudioData,
  ProcessarAudioResponses,
  RemoverAtendimentosData,
  RemoverAtendimentosResponses,
  RemoverAtendimentosErrors,
  AtualizarAtendimentosData,
  AtualizarAtendimentosResponses,
  AtualizarAtendimentosErrors,
  CriarAtendimentosV2Data,
  CriarAtendimentosV2Responses,
  CriarAtendimentosChunkData,
  CriarAtendimentosChunkResponses,
  FinalizarAtendimentosChunkData,
  FinalizarAtendimentosChunkResponses,
  LerFuncionalidadesData,
  LerFuncionalidadesResponses,
  LerFuncionalidadesErrors,
  CriarFuncionalidadesData,
  CriarFuncionalidadesResponses,
  CriarFuncionalidadesErrors,
  RemoverFuncionalidadesData,
  RemoverFuncionalidadesResponses,
  RemoverFuncionalidadesErrors,
  AtualizarFuncionalidadesData,
  AtualizarFuncionalidadesResponses,
  AtualizarFuncionalidadesErrors,
  CreateFileFilePostData,
  CreateFileFilePostResponses,
  StartRecordingData,
  StartRecordingResponses,
  AppendChunkData,
  AppendChunkResponses,
  GetFileByFilenameFileFilenameGetData,
  GetFileByFilenameFileFilenameGetResponses,
  GetMinioFileUrlByFilenameFileMinioFileUrlFilenameGetData,
  GetMinioFileUrlByFilenameFileMinioFileUrlFilenameGetResponses,
  DownloadFileFileDownloadFilenameGetData,
  DownloadFileFileDownloadFilenameGetResponses,
  DownloadFileFileDownloadFilenameGet2Data,
  DownloadFileFileDownloadFilenameGet2Responses,
  ListAllFilesFileFilesListGetData,
  ListAllFilesFileFilesListGetResponses,
  LerUsuariosData,
  LerUsuariosResponses,
  LerUsuariosErrors,
  CriarUsuariosData,
  CriarUsuariosResponses,
  CriarUsuariosErrors,
  RemoverUsuariosData,
  RemoverUsuariosResponses,
  RemoverUsuariosErrors,
  AtualizarUsuariosData,
  AtualizarUsuariosResponses,
  AtualizarUsuariosErrors,
  LinkUsuariosData,
  LinkUsuariosResponses,
  LinkUsuariosErrors,
  CriarUsuariosLinkData,
  CriarUsuariosLinkResponses,
  CriarUsuariosLinkErrors,
  LerUsuariosFuncionalidadesData,
  LerUsuariosFuncionalidadesResponses,
  LerUsuariosFuncionalidadesErrors,
  CriarUsuariosFuncionalidadesData,
  CriarUsuariosFuncionalidadesResponses,
  CriarUsuariosFuncionalidadesErrors,
  RemoverUsuariosFuncionalidadesData,
  RemoverUsuariosFuncionalidadesResponses,
  RemoverUsuariosFuncionalidadesErrors,
  AtualizarUsuariosFuncionalidadesData,
  AtualizarUsuariosFuncionalidadesResponses,
  AtualizarUsuariosFuncionalidadesErrors,
  FinishRecordingData,
  FinishRecordingResponses,
  LerPapeisData,
  LerPapeisResponses,
  LerPapeisErrors,
  CriarPapeisData,
  CriarPapeisResponses,
  CriarPapeisErrors,
  RemoverPapeisData,
  RemoverPapeisResponses,
  RemoverPapeisErrors,
  AtualizarPapeisData,
  AtualizarPapeisResponses,
  AtualizarPapeisErrors,
  LoginAccessTokenData,
  LoginAccessTokenResponses,
  LoginSessionTokenData,
  LoginSessionTokenResponses,
  EsqueciSenhaData,
  EsqueciSenhaResponses,
  EsqueciSenhaCodigoData,
  EsqueciSenhaCodigoResponses,
  NovaSenhaData,
  NovaSenhaResponses,
  LerPlanosData,
  LerPlanosResponses,
  LerPlanosErrors,
  CriarPlanosData,
  CriarPlanosResponses,
  CriarPlanosErrors,
  RemoverPlanosData,
  RemoverPlanosResponses,
  RemoverPlanosErrors,
  AtualizarPlanosData,
  AtualizarPlanosResponses,
  AtualizarPlanosErrors,
  LerPapeisFuncionalidadesData,
  LerPapeisFuncionalidadesResponses,
  LerPapeisFuncionalidadesErrors,
  CriarPapeisFuncionalidadesData,
  CriarPapeisFuncionalidadesResponses,
  CriarPapeisFuncionalidadesErrors,
  RemoverPapeisFuncionalidadesData,
  RemoverPapeisFuncionalidadesResponses,
  RemoverPapeisFuncionalidadesErrors,
  AtualizarPapeisFuncionalidadesData,
  AtualizarPapeisFuncionalidadesResponses,
  AtualizarPapeisFuncionalidadesErrors,
  LerEquipesData,
  LerEquipesResponses,
  LerEquipesErrors,
  CriarEquipesData,
  CriarEquipesResponses,
  CriarEquipesErrors,
  RemoverEquipesData,
  RemoverEquipesResponses,
  RemoverEquipesErrors,
  AtualizarEquipesData,
  AtualizarEquipesResponses,
  AtualizarEquipesErrors,
  LerEquipeUsuariosData,
  LerEquipeUsuariosResponses,
  LerEquipeUsuariosErrors,
  CriarEquipeUsuariosData,
  CriarEquipeUsuariosResponses,
  CriarEquipeUsuariosErrors,
  RemoverEquipeUsuariosData,
  RemoverEquipeUsuariosResponses,
  RemoverEquipeUsuariosErrors,
  AtualizarEquipeUsuariosData,
  AtualizarEquipeUsuariosResponses,
  AtualizarEquipeUsuariosErrors,
  LerTemplatesData,
  LerTemplatesResponses,
  LerTemplatesErrors,
  CriarTemplatesData,
  CriarTemplatesResponses,
  CriarTemplatesErrors,
  RemoverTemplatesData,
  RemoverTemplatesResponses,
  RemoverTemplatesErrors,
  AtualizarTemplatesData,
  AtualizarTemplatesResponses,
  AtualizarTemplatesErrors,
  LerEmpresasData,
  LerEmpresasResponses,
  LerEmpresasErrors,
  CriarEmpresasData,
  CriarEmpresasResponses,
  CriarEmpresasErrors,
  LerEmpresasTenantData,
  LerEmpresasTenantResponses,
  LerEmpresasTenantErrors,
  RemoverEmpresasData,
  RemoverEmpresasResponses,
  RemoverEmpresasErrors,
  AtualizarEmpresasData,
  AtualizarEmpresasResponses,
  AtualizarEmpresasErrors,
  UpdateTranscriptionWebhookTranscriptionPatchData,
  UpdateTranscriptionWebhookTranscriptionPatchResponses,
  UpdateRelatorioWebhookRelatorioPatchData,
  UpdateRelatorioWebhookRelatorioPatchResponses,
} from './types.gen'
import { client as _heyApiClient } from './client.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

/**
 * List Tenants
 * Lista todos os tenants disponíveis no sistema
 */
export const listTenantsTenantsGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListTenantsTenantsGetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ListTenantsTenantsGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/tenants/',
    ...options,
  })
}

/**
 * Remove Tenant
 */
export const removeTenantTenantsTenantIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RemoveTenantTenantsTenantIdDeleteData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    RemoveTenantTenantsTenantIdDeleteResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/tenants/{tenant_id}',
    ...options,
  })
}

/**
 * Ler Atendimentos
 */
export const lerAtendimentos = <ThrowOnError extends boolean = false>(
  options?: Options<LerAtendimentosData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    LerAtendimentosResponses,
    LerAtendimentosErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/atendimentos/',
    ...options,
  })
}

/**
 * Criar Atendimentos
 */
export const criarAtendimentos = <ThrowOnError extends boolean = false>(
  options: Options<CriarAtendimentosData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CriarAtendimentosResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/atendimentos/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Processar Audio
 */
export const processarAudio = <ThrowOnError extends boolean = false>(
  options?: Options<ProcessarAudioData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ProcessarAudioResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/atendimentos/processar-audio',
    ...options,
  })
}

/**
 * Remover Atendimentos
 */
export const removerAtendimentos = <ThrowOnError extends boolean = false>(
  options: Options<RemoverAtendimentosData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    RemoverAtendimentosResponses,
    RemoverAtendimentosErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/atendimentos/{id}',
    ...options,
  })
}

/**
 * Atualizar Atendimentos
 */
export const atualizarAtendimentos = <ThrowOnError extends boolean = false>(
  options: Options<AtualizarAtendimentosData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    AtualizarAtendimentosResponses,
    AtualizarAtendimentosErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/atendimentos/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Criar Atendimentos
 */
export const criarAtendimentosV2 = <ThrowOnError extends boolean = false>(
  options?: Options<CriarAtendimentosV2Data, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).post<
    CriarAtendimentosV2Responses,
    unknown,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/atendimentos/v2/',
    ...options,
    headers: {
      'Content-Type': null,
      ...options?.headers,
    },
  })
}

/**
 * Criar Atendimentos
 */
export const criarAtendimentosChunk = <ThrowOnError extends boolean = false>(
  options?: Options<CriarAtendimentosChunkData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).post<
    CriarAtendimentosChunkResponses,
    unknown,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/atendimentos/v2/chunk-data',
    ...options,
    headers: {
      'Content-Type': null,
      ...options?.headers,
    },
  })
}

/**
 * Finalizar Atendimentos
 */
export const finalizarAtendimentosChunk = <
  ThrowOnError extends boolean = false,
>(
  options: Options<FinalizarAtendimentosChunkData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    FinalizarAtendimentosChunkResponses,
    unknown,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/atendimentos/v2/finalizar-atendimento',
    ...options,
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...options.headers,
    },
  })
}

/**
 * Ler Funcionalidades
 */
export const lerFuncionalidades = <ThrowOnError extends boolean = false>(
  options?: Options<LerFuncionalidadesData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    LerFuncionalidadesResponses,
    LerFuncionalidadesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/funcionalidades/',
    ...options,
  })
}

/**
 * Criar Funcionalidades
 */
export const criarFuncionalidades = <ThrowOnError extends boolean = false>(
  options: Options<CriarFuncionalidadesData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CriarFuncionalidadesResponses,
    CriarFuncionalidadesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/funcionalidades/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Remover Funcionalidades
 */
export const removerFuncionalidades = <ThrowOnError extends boolean = false>(
  options: Options<RemoverFuncionalidadesData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    RemoverFuncionalidadesResponses,
    RemoverFuncionalidadesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/funcionalidades/{id}',
    ...options,
  })
}

/**
 * Atualizar Funcionalidades
 */
export const atualizarFuncionalidades = <ThrowOnError extends boolean = false>(
  options: Options<AtualizarFuncionalidadesData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    AtualizarFuncionalidadesResponses,
    AtualizarFuncionalidadesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/funcionalidades/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Cria novo Arquivo
 * Cria um novo arquivo.
 *
 * Args:
 * file (UploadFile): O arquivo a ser enviado.
 * type_data (FileType): O tipo de arquivo a ser salvo.
 *
 * Returns:
 * str: O nome do arquivo salvo.
 *
 * Raises:
 * HTTPException: Se ocorrer um erro durante o processo de criação do arquivo.
 */
export const createFileFilePost = <ThrowOnError extends boolean = false>(
  options: Options<CreateFileFilePostData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateFileFilePostResponses,
    unknown,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    responseType: 'json',
    url: '/file/',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  })
}

/**
 * Inicia nova gravação
 * Inicia uma nova gravação criando um arquivo vazio
 */
export const startRecording = <ThrowOnError extends boolean = false>(
  options?: Options<StartRecordingData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).post<
    StartRecordingResponses,
    unknown,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseType: 'json',
    url: '/file/start-recording',
    ...options,
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...options?.headers,
    },
  })
}

/**
 * Adiciona chunk à gravação
 * Adiciona um chunk de áudio à gravação existente
 */
export const appendChunk = <ThrowOnError extends boolean = false>(
  options: Options<AppendChunkData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    AppendChunkResponses,
    unknown,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    responseType: 'json',
    url: '/file/append-chunk',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  })
}

/**
 * Visualizar Arquivo
 */
export const getFileByFilenameFileFilenameGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetFileByFilenameFileFilenameGetData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetFileByFilenameFileFilenameGetResponses,
    unknown,
    ThrowOnError
  >({
    url: '/file/{filename}',
    ...options,
  })
}

/**
 * Visualizar Arquivo
 */
export const getMinioFileUrlByFilenameFileMinioFileUrlFilenameGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetMinioFileUrlByFilenameFileMinioFileUrlFilenameGetData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).get<
    GetMinioFileUrlByFilenameFileMinioFileUrlFilenameGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/file/minio-file-url/{filename}',
    ...options,
  })
}

/**
 * Download de Arquivo
 */
export const downloadFileFileDownloadFilenameGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DownloadFileFileDownloadFilenameGetData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    DownloadFileFileDownloadFilenameGetResponses,
    unknown,
    ThrowOnError
  >({
    url: '/file/download/{filename}',
    ...options,
  })
}

/**
 * Download de Arquivo
 */
export const downloadFileFileDownloadFilenameGet2 = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DownloadFileFileDownloadFilenameGet2Data, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).head<
    DownloadFileFileDownloadFilenameGet2Responses,
    unknown,
    ThrowOnError
  >({
    url: '/file/download/{filename}',
    ...options,
  })
}

/**
 * Listar todos os arquivos
 */
export const listAllFilesFileFilesListGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListAllFilesFileFilesListGetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ListAllFilesFileFilesListGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/file/files/list/',
    ...options,
  })
}

/**
 * Ler Usuarios
 */
export const lerUsuarios = <ThrowOnError extends boolean = false>(
  options?: Options<LerUsuariosData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    LerUsuariosResponses,
    LerUsuariosErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/usuarios/',
    ...options,
  })
}

/**
 * Criar Usuarios
 */
export const criarUsuarios = <ThrowOnError extends boolean = false>(
  options: Options<CriarUsuariosData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CriarUsuariosResponses,
    CriarUsuariosErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/usuarios/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Remover Usuarios
 */
export const removerUsuarios = <ThrowOnError extends boolean = false>(
  options: Options<RemoverUsuariosData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    RemoverUsuariosResponses,
    RemoverUsuariosErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/usuarios/{id}',
    ...options,
  })
}

/**
 * Atualizar Usuarios
 */
export const atualizarUsuarios = <ThrowOnError extends boolean = false>(
  options: Options<AtualizarUsuariosData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    AtualizarUsuariosResponses,
    AtualizarUsuariosErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/usuarios/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Gerar Link Usuarios
 */
export const linkUsuarios = <ThrowOnError extends boolean = false>(
  options: Options<LinkUsuariosData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    LinkUsuariosResponses,
    LinkUsuariosErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/usuarios/link-cadastro',
    ...options,
  })
}

/**
 * Criar Link Usuarios
 */
export const criarUsuariosLink = <ThrowOnError extends boolean = false>(
  options: Options<CriarUsuariosLinkData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CriarUsuariosLinkResponses,
    CriarUsuariosLinkErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/usuarios/link-cadastro/{token}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Ler Usuarios Funcionalidades
 */
export const lerUsuariosFuncionalidades = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<LerUsuariosFuncionalidadesData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    LerUsuariosFuncionalidadesResponses,
    LerUsuariosFuncionalidadesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/usuarios-funcionalidades/',
    ...options,
  })
}

/**
 * Criar Usuarios Funcionalidades
 */
export const criarUsuariosFuncionalidades = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CriarUsuariosFuncionalidadesData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CriarUsuariosFuncionalidadesResponses,
    CriarUsuariosFuncionalidadesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/usuarios-funcionalidades/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Remover Usuarios Funcionalidades
 */
export const removerUsuariosFuncionalidades = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RemoverUsuariosFuncionalidadesData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    RemoverUsuariosFuncionalidadesResponses,
    RemoverUsuariosFuncionalidadesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/usuarios-funcionalidades/{id}',
    ...options,
  })
}

/**
 * Atualizar Usuarios Funcionalidades
 */
export const atualizarUsuariosFuncionalidades = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AtualizarUsuariosFuncionalidadesData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    AtualizarUsuariosFuncionalidadesResponses,
    AtualizarUsuariosFuncionalidadesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/usuarios-funcionalidades/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Finaliza gravação
 * Finaliza a gravação e inicia o processamento do áudio em segundo plano
 */
export const finishRecording = <ThrowOnError extends boolean = false>(
  options: Options<FinishRecordingData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    FinishRecordingResponses,
    unknown,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/file/finish-recording',
    ...options,
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...options.headers,
    },
  })
}

/**
 * Ler Papeis
 */
export const lerPapeis = <ThrowOnError extends boolean = false>(
  options?: Options<LerPapeisData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    LerPapeisResponses,
    LerPapeisErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/papeis/',
    ...options,
  })
}

/**
 * Criar Papeis
 */
export const criarPapeis = <ThrowOnError extends boolean = false>(
  options: Options<CriarPapeisData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CriarPapeisResponses,
    CriarPapeisErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/papeis/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Remover Papeis
 */
export const removerPapeis = <ThrowOnError extends boolean = false>(
  options: Options<RemoverPapeisData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    RemoverPapeisResponses,
    RemoverPapeisErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/papeis/{id}',
    ...options,
  })
}

/**
 * Atualizar Papeis
 */
export const atualizarPapeis = <ThrowOnError extends boolean = false>(
  options: Options<AtualizarPapeisData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    AtualizarPapeisResponses,
    AtualizarPapeisErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/papeis/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Login
 * Logar
 */
export const loginAccessToken = <ThrowOnError extends boolean = false>(
  options: Options<LoginAccessTokenData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    LoginAccessTokenResponses,
    unknown,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseType: 'json',
    url: '/login/access-token',
    ...options,
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...options.headers,
    },
  })
}

/**
 * Login
 * Logar com sessão
 */
export const loginSessionToken = <ThrowOnError extends boolean = false>(
  options: Options<LoginSessionTokenData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    LoginSessionTokenResponses,
    unknown,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseType: 'json',
    url: '/login/session-token',
    ...options,
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...options.headers,
    },
  })
}

/**
 * Esqueci Senha
 * Esqueci minha senha
 */
export const esqueciSenha = <ThrowOnError extends boolean = false>(
  options: Options<EsqueciSenhaData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    EsqueciSenhaResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/esqueci-senha/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Redefinir Senha Codigo
 * Compara o codigo enviado para o email
 */
export const esqueciSenhaCodigo = <ThrowOnError extends boolean = false>(
  options: Options<EsqueciSenhaCodigoData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    EsqueciSenhaCodigoResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/esqueci-senha/code',
    ...options,
  })
}

/**
 * Put Password
 * Altera a senha do usuarios
 */
export const novaSenha = <ThrowOnError extends boolean = false>(
  options: Options<NovaSenhaData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).put<
    NovaSenhaResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/nova-senha/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Ler Planos
 */
export const lerPlanos = <ThrowOnError extends boolean = false>(
  options?: Options<LerPlanosData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    LerPlanosResponses,
    LerPlanosErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/planos/',
    ...options,
  })
}

/**
 * Criar Planos
 */
export const criarPlanos = <ThrowOnError extends boolean = false>(
  options: Options<CriarPlanosData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CriarPlanosResponses,
    CriarPlanosErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/planos/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Remover Planos
 */
export const removerPlanos = <ThrowOnError extends boolean = false>(
  options: Options<RemoverPlanosData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    RemoverPlanosResponses,
    RemoverPlanosErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/planos/{id}',
    ...options,
  })
}

/**
 * Atualizar Planos
 */
export const atualizarPlanos = <ThrowOnError extends boolean = false>(
  options: Options<AtualizarPlanosData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    AtualizarPlanosResponses,
    AtualizarPlanosErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/planos/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Ler Papeis Funcionalidades
 */
export const lerPapeisFuncionalidades = <ThrowOnError extends boolean = false>(
  options?: Options<LerPapeisFuncionalidadesData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    LerPapeisFuncionalidadesResponses,
    LerPapeisFuncionalidadesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/papeis-funcionalidades/',
    ...options,
  })
}

/**
 * Criar Papeis Funcionalidades
 */
export const criarPapeisFuncionalidades = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CriarPapeisFuncionalidadesData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CriarPapeisFuncionalidadesResponses,
    CriarPapeisFuncionalidadesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/papeis-funcionalidades/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Remover Papeis Funcionalidades
 */
export const removerPapeisFuncionalidades = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RemoverPapeisFuncionalidadesData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    RemoverPapeisFuncionalidadesResponses,
    RemoverPapeisFuncionalidadesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/papeis-funcionalidades/{id}',
    ...options,
  })
}

/**
 * Atualizar Papeis Funcionalidades
 */
export const atualizarPapeisFuncionalidades = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AtualizarPapeisFuncionalidadesData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    AtualizarPapeisFuncionalidadesResponses,
    AtualizarPapeisFuncionalidadesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/papeis-funcionalidades/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Ler Equipes
 */
export const lerEquipes = <ThrowOnError extends boolean = false>(
  options?: Options<LerEquipesData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    LerEquipesResponses,
    LerEquipesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/equipes/',
    ...options,
  })
}

/**
 * Criar Equipes
 */
export const criarEquipes = <ThrowOnError extends boolean = false>(
  options: Options<CriarEquipesData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CriarEquipesResponses,
    CriarEquipesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/equipes/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Remover Equipes
 */
export const removerEquipes = <ThrowOnError extends boolean = false>(
  options: Options<RemoverEquipesData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    RemoverEquipesResponses,
    RemoverEquipesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/equipes/{id}',
    ...options,
  })
}

/**
 * Atualizar Equipes
 */
export const atualizarEquipes = <ThrowOnError extends boolean = false>(
  options: Options<AtualizarEquipesData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    AtualizarEquipesResponses,
    AtualizarEquipesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/equipes/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Ler Equipe Usuarios
 */
export const lerEquipeUsuarios = <ThrowOnError extends boolean = false>(
  options?: Options<LerEquipeUsuariosData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    LerEquipeUsuariosResponses,
    LerEquipeUsuariosErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/equipe-usuarios/',
    ...options,
  })
}

/**
 * Criar Equipe Usuarios
 */
export const criarEquipeUsuarios = <ThrowOnError extends boolean = false>(
  options: Options<CriarEquipeUsuariosData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CriarEquipeUsuariosResponses,
    CriarEquipeUsuariosErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/equipe-usuarios/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Remover Equipe Usuarios
 */
export const removerEquipeUsuarios = <ThrowOnError extends boolean = false>(
  options: Options<RemoverEquipeUsuariosData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    RemoverEquipeUsuariosResponses,
    RemoverEquipeUsuariosErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/equipe-usuarios/{id}',
    ...options,
  })
}

/**
 * Atualizar Equipe Usuarios
 */
export const atualizarEquipeUsuarios = <ThrowOnError extends boolean = false>(
  options: Options<AtualizarEquipeUsuariosData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    AtualizarEquipeUsuariosResponses,
    AtualizarEquipeUsuariosErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/equipe-usuarios/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Ler Templates
 */
export const lerTemplates = <ThrowOnError extends boolean = false>(
  options?: Options<LerTemplatesData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    LerTemplatesResponses,
    LerTemplatesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/templates/',
    ...options,
  })
}

/**
 * Criar Templates
 */
export const criarTemplates = <ThrowOnError extends boolean = false>(
  options: Options<CriarTemplatesData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CriarTemplatesResponses,
    CriarTemplatesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/templates/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Remover Templates
 */
export const removerTemplates = <ThrowOnError extends boolean = false>(
  options: Options<RemoverTemplatesData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    RemoverTemplatesResponses,
    RemoverTemplatesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/templates/{id}',
    ...options,
  })
}

/**
 * Atualizar Templates
 */
export const atualizarTemplates = <ThrowOnError extends boolean = false>(
  options: Options<AtualizarTemplatesData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    AtualizarTemplatesResponses,
    AtualizarTemplatesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/templates/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Ler Empresas
 */
export const lerEmpresas = <ThrowOnError extends boolean = false>(
  options?: Options<LerEmpresasData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    LerEmpresasResponses,
    LerEmpresasErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/empresas/',
    ...options,
  })
}

/**
 * Criar Empresas
 */
export const criarEmpresas = <ThrowOnError extends boolean = false>(
  options: Options<CriarEmpresasData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CriarEmpresasResponses,
    CriarEmpresasErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/empresas/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Ler Empresas
 */
export const lerEmpresasTenant = <ThrowOnError extends boolean = false>(
  options?: Options<LerEmpresasTenantData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    LerEmpresasTenantResponses,
    LerEmpresasTenantErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/empresas/tenant',
    ...options,
  })
}

/**
 * Remover Empresas
 */
export const removerEmpresas = <ThrowOnError extends boolean = false>(
  options: Options<RemoverEmpresasData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    RemoverEmpresasResponses,
    RemoverEmpresasErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/empresas/{id}',
    ...options,
  })
}

/**
 * Atualizar Empresas
 */
export const atualizarEmpresas = <ThrowOnError extends boolean = false>(
  options: Options<AtualizarEmpresasData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    AtualizarEmpresasResponses,
    AtualizarEmpresasErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/empresas/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Update Transcription
 */
export const updateTranscriptionWebhookTranscriptionPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateTranscriptionWebhookTranscriptionPatchData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateTranscriptionWebhookTranscriptionPatchResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/webhook/transcription',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Update Relatorio
 */
export const updateRelatorioWebhookRelatorioPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateRelatorioWebhookRelatorioPatchData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateRelatorioWebhookRelatorioPatchResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/webhook/relatorio',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}
