// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type Options as Options2,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from './client'
import { client } from './client.gen'
import type {
  AtualizarFuncionalidadesData,
  AtualizarFuncionalidadesErrors,
  AtualizarFuncionalidadesResponses,
  AtualizarPapeisData,
  AtualizarPapeisErrors,
  AtualizarPapeisFuncionalidadesData,
  AtualizarPapeisFuncionalidadesErrors,
  AtualizarPapeisFuncionalidadesResponses,
  AtualizarPapeisResponses,
  AtualizarTenantsData,
  AtualizarTenantsErrors,
  AtualizarTenantsResponses,
  AtualizarUsuariosData,
  AtualizarUsuariosErrors,
  AtualizarUsuariosFuncionalidadesData,
  AtualizarUsuariosFuncionalidadesErrors,
  AtualizarUsuariosFuncionalidadesResponses,
  AtualizarUsuariosResponses,
  CriarFuncionalidadesData,
  CriarFuncionalidadesErrors,
  CriarFuncionalidadesResponses,
  CriarPapeisData,
  CriarPapeisErrors,
  CriarPapeisFuncionalidadesData,
  CriarPapeisFuncionalidadesErrors,
  CriarPapeisFuncionalidadesResponses,
  CriarPapeisResponses,
  CriarTenantsData,
  CriarTenantsErrors,
  CriarTenantsResponses,
  CriarUsuariosData,
  CriarUsuariosErrors,
  CriarUsuariosFuncionalidadesData,
  CriarUsuariosFuncionalidadesErrors,
  CriarUsuariosFuncionalidadesResponses,
  CriarUsuariosResponses,
  EsqueciSenhaCodigoData,
  EsqueciSenhaCodigoResponses,
  EsqueciSenhaData,
  EsqueciSenhaResponses,
  LerFuncionalidadesData,
  LerFuncionalidadesErrors,
  LerFuncionalidadesResponses,
  LerPapeisData,
  LerPapeisErrors,
  LerPapeisFuncionalidadesData,
  LerPapeisFuncionalidadesErrors,
  LerPapeisFuncionalidadesResponses,
  LerPapeisResponses,
  LerTenantsData,
  LerTenantsErrors,
  LerTenantsResponses,
  LerUsuariosData,
  LerUsuariosErrors,
  LerUsuariosFuncionalidadesData,
  LerUsuariosFuncionalidadesErrors,
  LerUsuariosFuncionalidadesResponses,
  LerUsuariosResponses,
  LoginAccessTokenData,
  LoginAccessTokenResponses,
  LoginSessionTokenData,
  LoginSessionTokenResponses,
  NovaSenhaData,
  NovaSenhaResponses,
  RemoverFuncionalidadesData,
  RemoverFuncionalidadesErrors,
  RemoverFuncionalidadesResponses,
  RemoverPapeisData,
  RemoverPapeisErrors,
  RemoverPapeisFuncionalidadesData,
  RemoverPapeisFuncionalidadesErrors,
  RemoverPapeisFuncionalidadesResponses,
  RemoverPapeisResponses,
  RemoverTenantsData,
  RemoverTenantsErrors,
  RemoverTenantsResponses,
  RemoverUsuariosData,
  RemoverUsuariosErrors,
  RemoverUsuariosFuncionalidadesData,
  RemoverUsuariosFuncionalidadesErrors,
  RemoverUsuariosFuncionalidadesResponses,
  RemoverUsuariosResponses,
} from './types.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

/**
 * Ler Funcionalidades
 */
export const lerFuncionalidades = <ThrowOnError extends boolean = false>(
  options?: Options<LerFuncionalidadesData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    LerFuncionalidadesResponses,
    LerFuncionalidadesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/funcionalidades/',
    ...options,
  })
}

/**
 * Criar Funcionalidades
 */
export const criarFuncionalidades = <ThrowOnError extends boolean = false>(
  options: Options<CriarFuncionalidadesData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    CriarFuncionalidadesResponses,
    CriarFuncionalidadesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
      {
        name: 'x-tenant-id',
        type: 'apiKey',
      },
    ],
    url: '/funcionalidades/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Remover Funcionalidades
 */
export const removerFuncionalidades = <ThrowOnError extends boolean = false>(
  options: Options<RemoverFuncionalidadesData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    RemoverFuncionalidadesResponses,
    RemoverFuncionalidadesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
      {
        name: 'x-tenant-id',
        type: 'apiKey',
      },
    ],
    url: '/funcionalidades/{id}',
    ...options,
  })
}

/**
 * Atualizar Funcionalidades
 */
export const atualizarFuncionalidades = <ThrowOnError extends boolean = false>(
  options: Options<AtualizarFuncionalidadesData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    AtualizarFuncionalidadesResponses,
    AtualizarFuncionalidadesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
      {
        name: 'x-tenant-id',
        type: 'apiKey',
      },
    ],
    url: '/funcionalidades/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Ler Tenants
 */
export const lerTenants = <ThrowOnError extends boolean = false>(
  options?: Options<LerTenantsData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    LerTenantsResponses,
    LerTenantsErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
      {
        name: 'x-tenant-id',
        type: 'apiKey',
      },
    ],
    url: '/tenants/',
    ...options,
  })
}

/**
 * Criar Tenants
 */
export const criarTenants = <ThrowOnError extends boolean = false>(
  options: Options<CriarTenantsData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    CriarTenantsResponses,
    CriarTenantsErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
      {
        name: 'x-tenant-id',
        type: 'apiKey',
      },
    ],
    url: '/tenants/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Remover Tenants
 */
export const removerTenants = <ThrowOnError extends boolean = false>(
  options: Options<RemoverTenantsData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    RemoverTenantsResponses,
    RemoverTenantsErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
      {
        name: 'x-tenant-id',
        type: 'apiKey',
      },
    ],
    url: '/tenants/{id}',
    ...options,
  })
}

/**
 * Atualizar Tenants
 */
export const atualizarTenants = <ThrowOnError extends boolean = false>(
  options: Options<AtualizarTenantsData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    AtualizarTenantsResponses,
    AtualizarTenantsErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
      {
        name: 'x-tenant-id',
        type: 'apiKey',
      },
    ],
    url: '/tenants/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Ler Usuarios
 */
export const lerUsuarios = <ThrowOnError extends boolean = false>(
  options?: Options<LerUsuariosData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    LerUsuariosResponses,
    LerUsuariosErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
      {
        name: 'x-tenant-id',
        type: 'apiKey',
      },
    ],
    url: '/usuarios/',
    ...options,
  })
}

/**
 * Criar Usuarios
 */
export const criarUsuarios = <ThrowOnError extends boolean = false>(
  options: Options<CriarUsuariosData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    CriarUsuariosResponses,
    CriarUsuariosErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
      {
        name: 'x-tenant-id',
        type: 'apiKey',
      },
    ],
    url: '/usuarios/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Remover Usuarios
 */
export const removerUsuarios = <ThrowOnError extends boolean = false>(
  options: Options<RemoverUsuariosData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    RemoverUsuariosResponses,
    RemoverUsuariosErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
      {
        name: 'x-tenant-id',
        type: 'apiKey',
      },
    ],
    url: '/usuarios/{id}',
    ...options,
  })
}

/**
 * Atualizar Usuarios
 */
export const atualizarUsuarios = <ThrowOnError extends boolean = false>(
  options: Options<AtualizarUsuariosData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    AtualizarUsuariosResponses,
    AtualizarUsuariosErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
      {
        name: 'x-tenant-id',
        type: 'apiKey',
      },
    ],
    url: '/usuarios/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Ler Usuarios Funcionalidades
 */
export const lerUsuariosFuncionalidades = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<LerUsuariosFuncionalidadesData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    LerUsuariosFuncionalidadesResponses,
    LerUsuariosFuncionalidadesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
      {
        name: 'x-tenant-id',
        type: 'apiKey',
      },
    ],
    url: '/usuarios-funcionalidades/',
    ...options,
  })
}

/**
 * Criar Usuarios Funcionalidades
 */
export const criarUsuariosFuncionalidades = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CriarUsuariosFuncionalidadesData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    CriarUsuariosFuncionalidadesResponses,
    CriarUsuariosFuncionalidadesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
      {
        name: 'x-tenant-id',
        type: 'apiKey',
      },
    ],
    url: '/usuarios-funcionalidades/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Remover Usuarios Funcionalidades
 */
export const removerUsuariosFuncionalidades = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RemoverUsuariosFuncionalidadesData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    RemoverUsuariosFuncionalidadesResponses,
    RemoverUsuariosFuncionalidadesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
      {
        name: 'x-tenant-id',
        type: 'apiKey',
      },
    ],
    url: '/usuarios-funcionalidades/{id}',
    ...options,
  })
}

/**
 * Atualizar Usuarios Funcionalidades
 */
export const atualizarUsuariosFuncionalidades = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AtualizarUsuariosFuncionalidadesData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    AtualizarUsuariosFuncionalidadesResponses,
    AtualizarUsuariosFuncionalidadesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
      {
        name: 'x-tenant-id',
        type: 'apiKey',
      },
    ],
    url: '/usuarios-funcionalidades/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Ler Papeis
 */
export const lerPapeis = <ThrowOnError extends boolean = false>(
  options?: Options<LerPapeisData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    LerPapeisResponses,
    LerPapeisErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
      {
        name: 'x-tenant-id',
        type: 'apiKey',
      },
    ],
    url: '/papeis/',
    ...options,
  })
}

/**
 * Criar Papeis
 */
export const criarPapeis = <ThrowOnError extends boolean = false>(
  options: Options<CriarPapeisData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    CriarPapeisResponses,
    CriarPapeisErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
      {
        name: 'x-tenant-id',
        type: 'apiKey',
      },
    ],
    url: '/papeis/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Remover Papeis
 */
export const removerPapeis = <ThrowOnError extends boolean = false>(
  options: Options<RemoverPapeisData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    RemoverPapeisResponses,
    RemoverPapeisErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
      {
        name: 'x-tenant-id',
        type: 'apiKey',
      },
    ],
    url: '/papeis/{id}',
    ...options,
  })
}

/**
 * Atualizar Papeis
 */
export const atualizarPapeis = <ThrowOnError extends boolean = false>(
  options: Options<AtualizarPapeisData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    AtualizarPapeisResponses,
    AtualizarPapeisErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
      {
        name: 'x-tenant-id',
        type: 'apiKey',
      },
    ],
    url: '/papeis/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Login
 *
 * Logar
 */
export const loginAccessToken = <ThrowOnError extends boolean = false>(
  options: Options<LoginAccessTokenData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    LoginAccessTokenResponses,
    unknown,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
      {
        name: 'x-tenant-id',
        type: 'apiKey',
      },
    ],
    url: '/login/access-token',
    ...options,
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...options.headers,
    },
  })
}

/**
 * Login
 *
 * Logar com sessão
 */
export const loginSessionToken = <ThrowOnError extends boolean = false>(
  options: Options<LoginSessionTokenData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    LoginSessionTokenResponses,
    unknown,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
      {
        name: 'x-tenant-id',
        type: 'apiKey',
      },
    ],
    url: '/login/session-token',
    ...options,
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...options.headers,
    },
  })
}

/**
 * Esqueci Senha
 *
 * Esqueci minha senha
 */
export const esqueciSenha = <ThrowOnError extends boolean = false>(
  options: Options<EsqueciSenhaData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    EsqueciSenhaResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
      {
        name: 'x-tenant-id',
        type: 'apiKey',
      },
    ],
    url: '/esqueci-senha/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Redefinir Senha Codigo
 *
 * Compara o codigo enviado para o email
 */
export const esqueciSenhaCodigo = <ThrowOnError extends boolean = false>(
  options: Options<EsqueciSenhaCodigoData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    EsqueciSenhaCodigoResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
      {
        name: 'x-tenant-id',
        type: 'apiKey',
      },
    ],
    url: '/esqueci-senha/code',
    ...options,
  })
}

/**
 * Put Password
 *
 * Altera a senha do usuarios
 */
export const novaSenha = <ThrowOnError extends boolean = false>(
  options: Options<NovaSenhaData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    NovaSenhaResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
      {
        name: 'x-tenant-id',
        type: 'apiKey',
      },
    ],
    url: '/nova-senha/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Ler Papeis Funcionalidades
 */
export const lerPapeisFuncionalidades = <ThrowOnError extends boolean = false>(
  options?: Options<LerPapeisFuncionalidadesData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    LerPapeisFuncionalidadesResponses,
    LerPapeisFuncionalidadesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
      {
        name: 'x-tenant-id',
        type: 'apiKey',
      },
    ],
    url: '/papeis-funcionalidades/',
    ...options,
  })
}

/**
 * Criar Papeis Funcionalidades
 */
export const criarPapeisFuncionalidades = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CriarPapeisFuncionalidadesData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    CriarPapeisFuncionalidadesResponses,
    CriarPapeisFuncionalidadesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
      {
        name: 'x-tenant-id',
        type: 'apiKey',
      },
    ],
    url: '/papeis-funcionalidades/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Remover Papeis Funcionalidades
 */
export const removerPapeisFuncionalidades = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RemoverPapeisFuncionalidadesData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    RemoverPapeisFuncionalidadesResponses,
    RemoverPapeisFuncionalidadesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
      {
        name: 'x-tenant-id',
        type: 'apiKey',
      },
    ],
    url: '/papeis-funcionalidades/{id}',
    ...options,
  })
}

/**
 * Atualizar Papeis Funcionalidades
 */
export const atualizarPapeisFuncionalidades = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AtualizarPapeisFuncionalidadesData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    AtualizarPapeisFuncionalidadesResponses,
    AtualizarPapeisFuncionalidadesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
      {
        name: 'x-tenant-id',
        type: 'apiKey',
      },
    ],
    url: '/papeis-funcionalidades/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}
