// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: `${string}://${string}` | (string & {})
}

/**
 * SortOp
 */
export const AppSchemaPapeisFuncionalidadesSchemaSortOp = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const

/**
 * SortOp
 */
export type AppSchemaPapeisFuncionalidadesSchemaSortOp =
  (typeof AppSchemaPapeisFuncionalidadesSchemaSortOp)[keyof typeof AppSchemaPapeisFuncionalidadesSchemaSortOp]

/**
 * CursorDirection
 */
export const AppSchemaPapeisFuncionalidadesSchemaCursorDirection = {
  NEXT: 'next',
  PREV: 'prev',
} as const

/**
 * CursorDirection
 */
export type AppSchemaPapeisFuncionalidadesSchemaCursorDirection =
  (typeof AppSchemaPapeisFuncionalidadesSchemaCursorDirection)[keyof typeof AppSchemaPapeisFuncionalidadesSchemaCursorDirection]

/**
 * UsuariosInclude
 */
export const UsuariosInclude = {
  NOME_USUARIO: 'nome_usuario',
  NOME_COMPLETO: 'nome_completo',
  TELEFONE: 'telefone',
  EMAIL: 'email',
  ATIVO: 'ativo',
  PAPEL_ID: 'papel_id',
  ID: 'id',
  CRIADO_EM: 'criado_em',
  ATUALIZADO_EM: 'atualizado_em',
} as const

/**
 * UsuariosInclude
 */
export type UsuariosInclude =
  (typeof UsuariosInclude)[keyof typeof UsuariosInclude]

/**
 * UsuariosFuncionalidadesInclude
 */
export const UsuariosFuncionalidadesInclude = {
  USUARIO_ID: 'usuario_id',
  FUNCIONALIDADE_ID: 'funcionalidade_id',
  ID: 'id',
  CRIADO_EM: 'criado_em',
  ATUALIZADO_EM: 'atualizado_em',
} as const

/**
 * UsuariosFuncionalidadesInclude
 */
export type UsuariosFuncionalidadesInclude =
  (typeof UsuariosFuncionalidadesInclude)[keyof typeof UsuariosFuncionalidadesInclude]

/**
 * UsuariosFuncionalidadesExpand
 */
export const UsuariosFuncionalidadesExpand = {
  FUNCIONALIDADES: 'funcionalidades',
  USUARIOS: 'usuarios',
} as const

/**
 * UsuariosFuncionalidadesExpand
 */
export type UsuariosFuncionalidadesExpand =
  (typeof UsuariosFuncionalidadesExpand)[keyof typeof UsuariosFuncionalidadesExpand]

/**
 * UsuariosExpand
 */
export const UsuariosExpand = {
  PAPEIS: 'papeis',
  USUARIOS_FUNCIONALIDADES: 'usuarios_funcionalidades',
} as const

/**
 * UsuariosExpand
 */
export type UsuariosExpand =
  (typeof UsuariosExpand)[keyof typeof UsuariosExpand]

/**
 * TenantsInclude
 */
export const TenantsInclude = {
  NOME: 'nome',
  SLUG: 'slug',
  SCHEMA_CRIADO: 'schema_criado',
  ATIVO: 'ativo',
  CONFIGURACAO: 'configuracao',
  ID: 'id',
  CRIADO_EM: 'criado_em',
  ATUALIZADO_EM: 'atualizado_em',
} as const

/**
 * TenantsInclude
 */
export type TenantsInclude =
  (typeof TenantsInclude)[keyof typeof TenantsInclude]

/**
 * ResponseLoginSessionToken
 */
export type ResponseLoginSessionToken = {
  user: GetUsuarios
}

/**
 * GetFuncionalidades
 */
export type GetFuncionalidades = {
  /**
   * Chave
   *
   * Chave de acesso autoincrementada
   */
  chave?: number | null
  /**
   * Nome
   *
   * Nome amigável da funcionalidades (ex: 'Excluir Cliente')
   */
  nome?: string
  /**
   * Escopo
   *
   * Identificador único no formato 'recurso:ação' (ex: 'client:delete')
   */
  escopo?: string
  /**
   * Caminho
   *
   * Endpoint da API (ex: '/api/client/{id}')
   */
  caminho?: string
  /**
   * Metodo
   *
   * Método HTTP (GET, POST, PUT, DELETE, etc)
   */
  metodo?: string
  /**
   * Descricao
   *
   * Descrição detalhada do propósito da funcionalidades
   */
  descricao?: string | null
  /**
   * Categoria
   *
   * Grupo funcional (ex: 'CRM', 'Financeiro', 'Relatórios')
   */
  categoria?: string | null
  /**
   * Sensivel
   *
   * Indica se é uma operação crítica/cuidado extra necessário
   */
  sensivel?: boolean | null
  /**
   * Versao
   *
   * Versão da funcionalidades para controle de evolução
   */
  versao?: number | null
  /**
   * Id
   *
   * Identificador único universal (UUIDv4) da entidade
   */
  id?: string
  /**
   * Criado Em
   *
   * Data e hora UTC da criação do registro
   */
  criado_em?: string
  /**
   * Atualizado Em
   *
   * Data e hora UTC da última atualização do registro (null se nunca foi atualizado)
   */
  atualizado_em?: string | null
}

/**
 * GetUsuariosFuncionalidades
 */
export type GetUsuariosFuncionalidades = {
  /**
   * Usuario Id
   *
   * Chave estrangeira referenciando o ID do Usuário
   */
  usuario_id?: string
  /**
   * Funcionalidade Id
   *
   * Chave estrangeira referenciando o ID da Funcionalidades
   */
  funcionalidade_id?: string
  /**
   * Id
   *
   * Identificador único universal (UUIDv4) da entidade
   */
  id?: string
  /**
   * Criado Em
   *
   * Data e hora UTC da criação do registro
   */
  criado_em?: string
  /**
   * Atualizado Em
   *
   * Data e hora UTC da última atualização do registro (null se nunca foi atualizado)
   */
  atualizado_em?: string | null
  funcionalidades?: GetFuncionalidades | null
}

/**
 * GetPapeis
 */
export type GetPapeis = {
  /**
   * Nome
   *
   * Nome identificador único do papeis (ex: 'Admin', 'Gerente')
   */
  nome?: string
  /**
   * Ativo
   *
   * Indica se o papeis está ativo e disponível para atribuição
   */
  ativo?: boolean
  /**
   * Descricao
   *
   * Descrição detalhada das permissões e responsabilidades do papeis
   */
  descricao?: string | null
  /**
   * Id
   *
   * Identificador único universal (UUIDv4) da entidade
   */
  id?: string
  /**
   * Criado Em
   *
   * Data e hora UTC da criação do registro
   */
  criado_em?: string
  /**
   * Atualizado Em
   *
   * Data e hora UTC da última atualização do registro (null se nunca foi atualizado)
   */
  atualizado_em?: string | null
}

/**
 * GetUsuarios
 */
export type GetUsuarios = {
  /**
   * Nome Usuario
   *
   * Nome único para login no sistema (case insensitive)
   */
  nome_usuario?: string
  /**
   * Nome Completo
   *
   * Nome completo do usuário
   */
  nome_completo?: string | null
  /**
   * Telefone
   *
   * Telefone de contato
   */
  telefone?: string | null
  /**
   * Email
   *
   * Endereço de e-mail válido do usuário
   */
  email?: string
  /**
   * Ativo
   *
   * Indica se a conta está ativa e pode acessar o sistema
   */
  ativo?: boolean
  /**
   * Papel Id
   *
   * Papeis principal atribuído ao usuário (pode ser nulo)
   */
  papel_id?: string | null
  /**
   * Id
   *
   * Identificador único universal (UUIDv4) da entidade
   */
  id?: string
  /**
   * Criado Em
   *
   * Data e hora UTC da criação do registro
   */
  criado_em?: string
  /**
   * Atualizado Em
   *
   * Data e hora UTC da última atualização do registro (null se nunca foi atualizado)
   */
  atualizado_em?: string | null
  papeis?: GetPapeis | null
  /**
   * Usuarios Funcionalidades
   */
  usuarios_funcionalidades?: Array<GetUsuariosFuncionalidades | null>
}

/**
 * ResponseLoginAcessToken
 */
export type ResponseLoginAcessToken = {
  /**
   * Access Token
   */
  access_token: string
  /**
   * Token Type
   */
  token_type: string
  /**
   * Permission
   */
  permission: Array<string> | null
  user: GetUsuarios
  /**
   * Papel
   */
  papel: string
}

/**
 * ResponseEsqueciSenhaCodigo
 */
export type ResponseEsqueciSenhaCodigo = {
  /**
   * Token
   */
  token: string
}

/**
 * ResponseEsqueciSenha
 */
export type ResponseEsqueciSenha = {
  /**
   * Token
   */
  token: string
}

/**
 * PostUsuariosFuncionalidades
 */
export type PostUsuariosFuncionalidades = {
  /**
   * Usuario Id
   *
   * Chave estrangeira referenciando o ID do Usuário
   */
  usuario_id: string
  /**
   * Funcionalidade Id
   *
   * Chave estrangeira referenciando o ID da Funcionalidades
   */
  funcionalidade_id: string
}

/**
 * PostUsuarios
 */
export type PostUsuarios = {
  /**
   * Nome Usuario
   *
   * Nome único para login no sistema (case insensitive)
   */
  nome_usuario: string
  /**
   * Nome Completo
   *
   * Nome completo do usuário
   */
  nome_completo?: string | null
  /**
   * Telefone
   *
   * Telefone de contato
   */
  telefone?: string | null
  /**
   * Email
   *
   * Endereço de e-mail válido do usuário
   */
  email: string
  /**
   * Senha
   *
   * Hash da senha do usuário (armazenado de forma criptografada)
   */
  senha: Blob | File
  /**
   * Ativo
   *
   * Indica se a conta está ativa e pode acessar o sistema
   */
  ativo?: boolean
  /**
   * Papel Id
   *
   * Papeis principal atribuído ao usuário (pode ser nulo)
   */
  papel_id?: string | null
}

/**
 * PostTenants
 */
export type PostTenants = {
  /**
   * Nome
   *
   * Nome único da tenant/organização
   */
  nome: string
  /**
   * Slug
   *
   * Slug único para identificação na URL (ex: nome-empresa)
   */
  slug: string
  /**
   * Schema Criado
   *
   * Indica se o schema foi criado e populado
   */
  schema_criado?: boolean
  /**
   * Ativo
   *
   * Indica se a tenant está ativa no sistema
   */
  ativo?: boolean
  /**
   * Configuracao
   *
   * Configurações customizadas em JSON
   */
  configuracao?: {
    [key: string]: unknown
  } | null
}

/**
 * PostPapeisFuncionalidades
 */
export type PostPapeisFuncionalidades = {
  /**
   * Papel Id
   *
   * Chave estrangeira referenciando o ID do Papeis
   */
  papel_id: string
  /**
   * Funcionalidade Id
   */
  funcionalidade_id: string
}

/**
 * PostPapeis
 */
export type PostPapeis = {
  /**
   * Nome
   *
   * Nome identificador único do papeis (ex: 'Admin', 'Gerente')
   */
  nome: string
  /**
   * Ativo
   *
   * Indica se o papeis está ativo e disponível para atribuição
   */
  ativo?: boolean
  /**
   * Descricao
   *
   * Descrição detalhada das permissões e responsabilidades do papeis
   */
  descricao?: string | null
}

/**
 * PostFuncionalidades
 */
export type PostFuncionalidades = {
  /**
   * Nome
   *
   * Nome amigável da funcionalidades (ex: 'Excluir Cliente')
   */
  nome: string
  /**
   * Escopo
   *
   * Identificador único no formato 'recurso:ação' (ex: 'client:delete')
   */
  escopo: string
  /**
   * Caminho
   *
   * Endpoint da API (ex: '/api/client/{id}')
   */
  caminho: string
  /**
   * Metodo
   *
   * Método HTTP (GET, POST, PUT, DELETE, etc)
   */
  metodo: string
  /**
   * Descricao
   *
   * Descrição detalhada do propósito da funcionalidades
   */
  descricao?: string | null
  /**
   * Categoria
   *
   * Grupo funcional (ex: 'CRM', 'Financeiro', 'Relatórios')
   */
  categoria?: string | null
  /**
   * Sensivel
   *
   * Indica se é uma operação crítica/cuidado extra necessário
   */
  sensivel?: boolean | null
  /**
   * Versao
   *
   * Versão da funcionalidades para controle de evolução
   */
  versao?: number | null
}

/**
 * PatchUsuariosFuncionalidades
 */
export type PatchUsuariosFuncionalidades = {
  /**
   * Usuario Id
   *
   * Chave estrangeira referenciando o ID do Usuário
   */
  usuario_id?: string | null
  /**
   * Funcionalidade Id
   *
   * Chave estrangeira referenciando o ID da Funcionalidades
   */
  funcionalidade_id?: string | null
}

/**
 * PatchUsuarios
 */
export type PatchUsuarios = {
  /**
   * Nome Usuario
   *
   * Nome único para login no sistema (case insensitive)
   */
  nome_usuario?: string | null
  /**
   * Nome Completo
   *
   * Nome completo do usuário
   */
  nome_completo?: string | null
  /**
   * Telefone
   *
   * Telefone de contato
   */
  telefone?: string | null
  /**
   * Email
   *
   * Endereço de e-mail válido do usuário
   */
  email?: string | null
  /**
   * Senha
   *
   * Hash da senha do usuário (armazenado de forma criptografada)
   */
  senha?: Blob | File | null
  /**
   * Ativo
   *
   * Indica se a conta está ativa e pode acessar o sistema
   */
  ativo?: boolean | null
  /**
   * Papel Id
   *
   * Papeis principal atribuído ao usuário (pode ser nulo)
   */
  papel_id?: string | null
}

/**
 * PatchTenants
 */
export type PatchTenants = {
  /**
   * Nome
   *
   * Nome único da tenant/organização
   */
  nome?: string | null
  /**
   * Slug
   *
   * Slug único para identificação na URL (ex: nome-empresa)
   */
  slug?: string | null
  /**
   * Schema Criado
   *
   * Indica se o schema foi criado e populado
   */
  schema_criado?: boolean | null
  /**
   * Ativo
   *
   * Indica se a tenant está ativa no sistema
   */
  ativo?: boolean | null
  /**
   * Configuracao
   *
   * Configurações customizadas em JSON
   */
  configuracao?: {
    [key: string]: unknown
  } | null
}

/**
 * PatchPapeisFuncionalidades
 */
export type PatchPapeisFuncionalidades = {
  /**
   * Papel Id
   *
   * Chave estrangeira referenciando o ID do Papeis
   */
  papel_id?: string | null
  /**
   * Funcionalidade Id
   */
  funcionalidade_id?: string | null
}

/**
 * PatchPapeis
 */
export type PatchPapeis = {
  /**
   * Nome
   *
   * Nome identificador único do papeis (ex: 'Admin', 'Gerente')
   */
  nome?: string | null
  /**
   * Ativo
   *
   * Indica se o papeis está ativo e disponível para atribuição
   */
  ativo?: boolean | null
  /**
   * Descricao
   *
   * Descrição detalhada das permissões e responsabilidades do papeis
   */
  descricao?: string | null
}

/**
 * PatchFuncionalidades
 */
export type PatchFuncionalidades = {
  /**
   * Nome
   *
   * Nome amigável da funcionalidades (ex: 'Excluir Cliente')
   */
  nome?: string | null
  /**
   * Escopo
   *
   * Identificador único no formato 'recurso:ação' (ex: 'client:delete')
   */
  escopo?: string | null
  /**
   * Caminho
   *
   * Endpoint da API (ex: '/api/client/{id}')
   */
  caminho?: string | null
  /**
   * Metodo
   *
   * Método HTTP (GET, POST, PUT, DELETE, etc)
   */
  metodo?: string | null
  /**
   * Descricao
   *
   * Descrição detalhada do propósito da funcionalidades
   */
  descricao?: string | null
  /**
   * Categoria
   *
   * Grupo funcional (ex: 'CRM', 'Financeiro', 'Relatórios')
   */
  categoria?: string | null
  /**
   * Sensivel
   *
   * Indica se é uma operação crítica/cuidado extra necessário
   */
  sensivel?: boolean | null
  /**
   * Versao
   *
   * Versão da funcionalidades para controle de evolução
   */
  versao?: number | null
}

/**
 * PapeisInclude
 */
export const PapeisInclude = {
  NOME: 'nome',
  ATIVO: 'ativo',
  DESCRICAO: 'descricao',
  ID: 'id',
  CRIADO_EM: 'criado_em',
  ATUALIZADO_EM: 'atualizado_em',
} as const

/**
 * PapeisInclude
 */
export type PapeisInclude = (typeof PapeisInclude)[keyof typeof PapeisInclude]

/**
 * PapeisFuncionalidadesInclude
 */
export const PapeisFuncionalidadesInclude = {
  PAPEL_ID: 'papel_id',
  FUNCIONALIDADE_ID: 'funcionalidade_id',
  ID: 'id',
  CRIADO_EM: 'criado_em',
  ATUALIZADO_EM: 'atualizado_em',
} as const

/**
 * PapeisFuncionalidadesInclude
 */
export type PapeisFuncionalidadesInclude =
  (typeof PapeisFuncionalidadesInclude)[keyof typeof PapeisFuncionalidadesInclude]

/**
 * PapeisFuncionalidadesExpand
 */
export const PapeisFuncionalidadesExpand = {
  FUNCIONALIDADES: 'funcionalidades',
  PAPEIS: 'papeis',
} as const

/**
 * PapeisFuncionalidadesExpand
 */
export type PapeisFuncionalidadesExpand =
  (typeof PapeisFuncionalidadesExpand)[keyof typeof PapeisFuncionalidadesExpand]

/**
 * NovaSenha
 */
export type NovaSenha = {
  /**
   * Senha
   *
   * Senha
   */
  senha: Blob | File
}

/**
 * Meta
 *
 * Metadados para operações
 */
export type Meta = {
  /**
   * Total Items
   *
   * Total de itens disponíveis
   */
  total_items?: number
  /**
   * Total Query
   *
   * Total de itens retornados na consulta
   */
  total_query?: number
  /**
   * Items Per Page
   *
   * Quantidade de itens por página
   */
  items_per_page?: number | null
  /**
   * Current Page
   *
   * Página atual
   */
  current_page?: number | null
  /**
   * Total Pages
   *
   * Total de páginas
   */
  total_pages?: number | null
  /**
   * Next Cursor
   *
   * Cursor para próxima página
   */
  next_cursor?: string | null
  /**
   * Prev Cursor
   *
   * Cursor para página anterior
   */
  prev_cursor?: string | null
  /**
   * Next Offset
   *
   * Offset para próxima página
   */
  next_offset?: number | null
  /**
   * Prev Offset
   *
   * Offset para página anterior
   */
  prev_offset?: number | null
  /**
   * Has Next
   *
   * Existem mais itens após os retornados
   */
  has_next?: boolean | null
  /**
   * Has Prev
   *
   * Existem itens antes dos retornados
   */
  has_prev?: boolean | null
}

/**
 * GetTenants
 */
export type GetTenants = {
  /**
   * Nome
   *
   * Nome único da tenant/organização
   */
  nome?: string
  /**
   * Slug
   *
   * Slug único para identificação na URL (ex: nome-empresa)
   */
  slug?: string
  /**
   * Schema Criado
   *
   * Indica se o schema foi criado e populado
   */
  schema_criado?: boolean
  /**
   * Ativo
   *
   * Indica se a tenant está ativa no sistema
   */
  ativo?: boolean
  /**
   * Configuracao
   *
   * Configurações customizadas em JSON
   */
  configuracao?: {
    [key: string]: unknown
  } | null
  /**
   * Id
   *
   * Identificador único universal (UUIDv4) da entidade
   */
  id?: string
  /**
   * Criado Em
   *
   * Data e hora UTC da criação do registro
   */
  criado_em?: string
  /**
   * Atualizado Em
   *
   * Data e hora UTC da última atualização do registro (null se nunca foi atualizado)
   */
  atualizado_em?: string | null
}

/**
 * GetPapeisFuncionalidades
 */
export type GetPapeisFuncionalidades = {
  /**
   * Papel Id
   *
   * Chave estrangeira referenciando o ID do Papeis
   */
  papel_id?: string
  /**
   * Funcionalidade Id
   */
  funcionalidade_id?: string
  /**
   * Id
   *
   * Identificador único universal (UUIDv4) da entidade
   */
  id?: string
  /**
   * Criado Em
   *
   * Data e hora UTC da criação do registro
   */
  criado_em?: string
  /**
   * Atualizado Em
   *
   * Data e hora UTC da última atualização do registro (null se nunca foi atualizado)
   */
  atualizado_em?: string | null
  funcionalidades?: GetFuncionalidades | null
  papeis?: GetPapeis | null
}

/**
 * FuncionalidadesInclude
 */
export const FuncionalidadesInclude = {
  CHAVE: 'chave',
  NOME: 'nome',
  ESCOPO: 'escopo',
  CAMINHO: 'caminho',
  METODO: 'metodo',
  DESCRICAO: 'descricao',
  CATEGORIA: 'categoria',
  SENSIVEL: 'sensivel',
  VERSAO: 'versao',
  ID: 'id',
  CRIADO_EM: 'criado_em',
  ATUALIZADO_EM: 'atualizado_em',
} as const

/**
 * FuncionalidadesInclude
 */
export type FuncionalidadesInclude =
  (typeof FuncionalidadesInclude)[keyof typeof FuncionalidadesInclude]

/**
 * EsqueciSenha
 */
export type EsqueciSenha = {
  /**
   * Email
   */
  email: string
}

/**
 * ErrorSchema
 */
export type ErrorSchema = {
  /**
   * Detail
   *
   * Lista de detalhes dos erros ocorridos
   */
  detail: Array<Detail>
}

/**
 * Detail
 */
export type Detail = {
  /**
   * Loc
   *
   * Lista de localizações onde o erro ocorreu
   */
  loc?: Array<string | number> | null
  /**
   * Msg
   *
   * Mensagem descritiva do erro
   */
  msg: string
  /**
   * Type
   *
   * Tipo/categoria do erro
   */
  type?: string | null
  /**
   * Debug
   *
   * Detalhes adicionais do erro retornados em desenvolvimento
   */
  debug?: string | null
}

/**
 * Body_login_session_token
 */
export type BodyLoginSessionToken = {
  /**
   * Username
   *
   * nome_usuario Documentar
   */
  username: string
  /**
   * Password
   *
   * senha Documentar
   */
  password: string
}

/**
 * Body_login_access_token
 */
export type BodyLoginAccessToken = {
  /**
   * Username
   *
   * nome_usuario Documentar
   */
  username: string
  /**
   * Password
   *
   * senha Documentar
   */
  password: string
}

/**
 * ApiSuccess[NoneType]
 */
export type ApiSuccessNoneType = {
  /**
   * Msg
   */
  msg?: string | null
  meta?: Meta | null
  /**
   * Data
   *
   * Lista de itens do tipo especificado
   */
  data?: Array<null> | null
}

/**
 * ApiSuccess[GetUsuarios]
 */
export type ApiSuccessGetUsuarios = {
  /**
   * Msg
   */
  msg?: string | null
  meta?: Meta | null
  /**
   * Data
   *
   * Lista de itens do tipo especificado
   */
  data?: Array<GetUsuarios> | null
}

/**
 * ApiSuccess[GetUsuariosFuncionalidades]
 */
export type ApiSuccessGetUsuariosFuncionalidades = {
  /**
   * Msg
   */
  msg?: string | null
  meta?: Meta | null
  /**
   * Data
   *
   * Lista de itens do tipo especificado
   */
  data?: Array<GetUsuariosFuncionalidades> | null
}

/**
 * ApiSuccess[GetTenants]
 */
export type ApiSuccessGetTenants = {
  /**
   * Msg
   */
  msg?: string | null
  meta?: Meta | null
  /**
   * Data
   *
   * Lista de itens do tipo especificado
   */
  data?: Array<GetTenants> | null
}

/**
 * ApiSuccess[GetPapeis]
 */
export type ApiSuccessGetPapeis = {
  /**
   * Msg
   */
  msg?: string | null
  meta?: Meta | null
  /**
   * Data
   *
   * Lista de itens do tipo especificado
   */
  data?: Array<GetPapeis> | null
}

/**
 * ApiSuccess[GetPapeisFuncionalidades]
 */
export type ApiSuccessGetPapeisFuncionalidades = {
  /**
   * Msg
   */
  msg?: string | null
  meta?: Meta | null
  /**
   * Data
   *
   * Lista de itens do tipo especificado
   */
  data?: Array<GetPapeisFuncionalidades> | null
}

/**
 * ApiSuccess[GetFuncionalidades]
 */
export type ApiSuccessGetFuncionalidades = {
  /**
   * Msg
   */
  msg?: string | null
  meta?: Meta | null
  /**
   * Data
   *
   * Lista de itens do tipo especificado
   */
  data?: Array<GetFuncionalidades> | null
}

export type LerFuncionalidadesData = {
  body?: never
  path?: never
  query?: {
    /**
     * All Data
     *
     * Retornar todas as correspondências ou apenas a primeira
     */
    all_data?: boolean
    /**
     * Chave
     *
     * Chave de acesso autoincrementada
     */
    chave?: string | null
    /**
     * Nome
     *
     * Nome amigável da funcionalidades (ex: 'Excluir Cliente')
     */
    nome?: string | null
    /**
     * Escopo
     *
     * Identificador único no formato 'recurso:ação' (ex: 'client:delete')
     */
    escopo?: string | null
    /**
     * Caminho
     *
     * Endpoint da API (ex: '/api/client/{id}')
     */
    caminho?: string | null
    /**
     * Metodo
     *
     * Método HTTP (GET, POST, PUT, DELETE, etc)
     */
    metodo?: string | null
    /**
     * Descricao
     *
     * Descrição detalhada do propósito da funcionalidades
     */
    descricao?: string | null
    /**
     * Categoria
     *
     * Grupo funcional (ex: 'CRM', 'Financeiro', 'Relatórios')
     */
    categoria?: string | null
    /**
     * Sensivel
     *
     * Indica se é uma operação crítica/cuidado extra necessário
     */
    sensivel?: string | null
    /**
     * Versao
     *
     * Versão da funcionalidades para controle de evolução
     */
    versao?: string | null
    /**
     * Id
     *
     * Identificador único universal (UUIDv4) da entidade
     */
    id?: string | null
    /**
     * Criado Em
     *
     * Data e hora UTC da criação do registro
     */
    criado_em?: string | null
    /**
     * Atualizado Em
     *
     * Data e hora UTC da última atualização do registro (null se nunca foi atualizado)
     */
    atualizado_em?: string | null
    /**
     * Limit
     *
     * Número máximo de itens a retornar
     */
    limit?: number | null
    /**
     * Offset
     *
     * Offset absoluto para paginação (alternativa a skip)
     */
    offset?: number | null
    /**
     * Cursor
     *
     * Valor do cursor para paginação baseada em cursor
     */
    cursor?: string | null
    /**
     * Campo a ser usado como cursor (padrão: 'id')
     */
    cursor_field?: FuncionalidadesInclude
    /**
     * Direção da paginação por cursor (next|prev)
     */
    cursor_direction?: AppSchemaPapeisFuncionalidadesSchemaCursorDirection
    /**
     * Include
     *
     * Atributos a incluir na resposta
     */
    include?: Array<FuncionalidadesInclude>
    /**
     * Exclude
     *
     * Atributos a excluir da resposta
     */
    exclude?: Array<FuncionalidadesInclude>
    /**
     * Count Only
     *
     * Retornar apenas a contagem total de itens, sem os dados
     */
    count_only?: boolean
    /**
     * Distinct
     *
     * Aplicar DISTINCT na consulta para evitar duplicatas
     */
    distinct?: boolean
    /**
     * operador da ordem do resultado (ASC | DESC)
     */
    sort_op?: AppSchemaPapeisFuncionalidadesSchemaSortOp
    /**
     * ordem do resultado (ex: criado_em)
     */
    sort_field?: FuncionalidadesInclude
  }
  url: '/funcionalidades/'
}

export type LerFuncionalidadesErrors = {
  /**
   * Erro na requisição
   */
  400: ErrorSchema
}

export type LerFuncionalidadesError =
  LerFuncionalidadesErrors[keyof LerFuncionalidadesErrors]

export type LerFuncionalidadesResponses = {
  /**
   * Successful Response
   */
  200: ApiSuccessGetFuncionalidades
}

export type LerFuncionalidadesResponse =
  LerFuncionalidadesResponses[keyof LerFuncionalidadesResponses]

export type CriarFuncionalidadesData = {
  body: PostFuncionalidades
  path?: never
  query?: never
  url: '/funcionalidades/'
}

export type CriarFuncionalidadesErrors = {
  /**
   * Erro na requisição
   */
  400: ErrorSchema
}

export type CriarFuncionalidadesError =
  CriarFuncionalidadesErrors[keyof CriarFuncionalidadesErrors]

export type CriarFuncionalidadesResponses = {
  /**
   * Successful Response
   */
  201: ApiSuccessNoneType
}

export type CriarFuncionalidadesResponse =
  CriarFuncionalidadesResponses[keyof CriarFuncionalidadesResponses]

export type RemoverFuncionalidadesData = {
  body?: never
  path: {
    /**
     * Id
     *
     * ID dado a ser removido
     */
    id: string
  }
  query?: never
  url: '/funcionalidades/{id}'
}

export type RemoverFuncionalidadesErrors = {
  /**
   * Erro na requisição
   */
  400: ErrorSchema
}

export type RemoverFuncionalidadesError =
  RemoverFuncionalidadesErrors[keyof RemoverFuncionalidadesErrors]

export type RemoverFuncionalidadesResponses = {
  /**
   * Successful Response
   */
  200: ApiSuccessNoneType
}

export type RemoverFuncionalidadesResponse =
  RemoverFuncionalidadesResponses[keyof RemoverFuncionalidadesResponses]

export type AtualizarFuncionalidadesData = {
  body: PatchFuncionalidades
  path: {
    /**
     * Id
     *
     * ID dado a ser atualizado
     */
    id: string
  }
  query?: never
  url: '/funcionalidades/{id}'
}

export type AtualizarFuncionalidadesErrors = {
  /**
   * Erro na requisição
   */
  400: ErrorSchema
}

export type AtualizarFuncionalidadesError =
  AtualizarFuncionalidadesErrors[keyof AtualizarFuncionalidadesErrors]

export type AtualizarFuncionalidadesResponses = {
  /**
   * Successful Response
   */
  200: ApiSuccessNoneType
}

export type AtualizarFuncionalidadesResponse =
  AtualizarFuncionalidadesResponses[keyof AtualizarFuncionalidadesResponses]

export type LerTenantsData = {
  body?: never
  path?: never
  query?: {
    /**
     * All Data
     *
     * Retornar todas as correspondências ou apenas a primeira
     */
    all_data?: boolean
    /**
     * Nome
     *
     * Nome único da tenant/organização
     */
    nome?: string | null
    /**
     * Slug
     *
     * Slug único para identificação na URL (ex: nome-empresa)
     */
    slug?: string | null
    /**
     * Schema Criado
     *
     * Indica se o schema foi criado e populado
     */
    schema_criado?: string | null
    /**
     * Ativo
     *
     * Indica se a tenant está ativa no sistema
     */
    ativo?: string | null
    /**
     * Configuracao
     *
     * Configurações customizadas em JSON
     */
    configuracao?: string | null
    /**
     * Id
     *
     * Identificador único universal (UUIDv4) da entidade
     */
    id?: string | null
    /**
     * Criado Em
     *
     * Data e hora UTC da criação do registro
     */
    criado_em?: string | null
    /**
     * Atualizado Em
     *
     * Data e hora UTC da última atualização do registro (null se nunca foi atualizado)
     */
    atualizado_em?: string | null
    /**
     * Limit
     *
     * Número máximo de itens a retornar
     */
    limit?: number | null
    /**
     * Offset
     *
     * Offset absoluto para paginação (alternativa a skip)
     */
    offset?: number | null
    /**
     * Cursor
     *
     * Valor do cursor para paginação baseada em cursor
     */
    cursor?: string | null
    /**
     * Campo a ser usado como cursor (padrão: 'id')
     */
    cursor_field?: TenantsInclude
    /**
     * Direção da paginação por cursor (next|prev)
     */
    cursor_direction?: AppSchemaPapeisFuncionalidadesSchemaCursorDirection
    /**
     * Include
     *
     * Atributos a incluir na resposta
     */
    include?: Array<TenantsInclude>
    /**
     * Exclude
     *
     * Atributos a excluir da resposta
     */
    exclude?: Array<TenantsInclude>
    /**
     * Count Only
     *
     * Retornar apenas a contagem total de itens, sem os dados
     */
    count_only?: boolean
    /**
     * Distinct
     *
     * Aplicar DISTINCT na consulta para evitar duplicatas
     */
    distinct?: boolean
    /**
     * operador da ordem do resultado (ASC | DESC)
     */
    sort_op?: AppSchemaPapeisFuncionalidadesSchemaSortOp
    /**
     * ordem do resultado (ex: criado_em)
     */
    sort_field?: TenantsInclude
  }
  url: '/tenants/'
}

export type LerTenantsErrors = {
  /**
   * Erro na requisição
   */
  400: ErrorSchema
}

export type LerTenantsError = LerTenantsErrors[keyof LerTenantsErrors]

export type LerTenantsResponses = {
  /**
   * Successful Response
   */
  200: ApiSuccessGetTenants
}

export type LerTenantsResponse = LerTenantsResponses[keyof LerTenantsResponses]

export type CriarTenantsData = {
  body: PostTenants
  path?: never
  query?: never
  url: '/tenants/'
}

export type CriarTenantsErrors = {
  /**
   * Erro na requisição
   */
  400: ErrorSchema
}

export type CriarTenantsError = CriarTenantsErrors[keyof CriarTenantsErrors]

export type CriarTenantsResponses = {
  /**
   * Successful Response
   */
  201: ApiSuccessNoneType
}

export type CriarTenantsResponse =
  CriarTenantsResponses[keyof CriarTenantsResponses]

export type RemoverTenantsData = {
  body?: never
  path: {
    /**
     * Id
     *
     * ID dado a ser removido
     */
    id: string
  }
  query?: never
  url: '/tenants/{id}'
}

export type RemoverTenantsErrors = {
  /**
   * Erro na requisição
   */
  400: ErrorSchema
}

export type RemoverTenantsError =
  RemoverTenantsErrors[keyof RemoverTenantsErrors]

export type RemoverTenantsResponses = {
  /**
   * Successful Response
   */
  200: ApiSuccessNoneType
}

export type RemoverTenantsResponse =
  RemoverTenantsResponses[keyof RemoverTenantsResponses]

export type AtualizarTenantsData = {
  body: PatchTenants
  path: {
    /**
     * Id
     *
     * ID dado a ser atualizado
     */
    id: string
  }
  query?: never
  url: '/tenants/{id}'
}

export type AtualizarTenantsErrors = {
  /**
   * Erro na requisição
   */
  400: ErrorSchema
}

export type AtualizarTenantsError =
  AtualizarTenantsErrors[keyof AtualizarTenantsErrors]

export type AtualizarTenantsResponses = {
  /**
   * Successful Response
   */
  200: ApiSuccessNoneType
}

export type AtualizarTenantsResponse =
  AtualizarTenantsResponses[keyof AtualizarTenantsResponses]

export type LerUsuariosData = {
  body?: never
  path?: never
  query?: {
    /**
     * All Data
     *
     * Retornar todas as correspondências ou apenas a primeira
     */
    all_data?: boolean
    /**
     * Nome Usuario
     *
     * Nome único para login no sistema (case insensitive)
     */
    nome_usuario?: string | null
    /**
     * Nome Completo
     *
     * Nome completo do usuário
     */
    nome_completo?: string | null
    /**
     * Telefone
     *
     * Telefone de contato
     */
    telefone?: string | null
    /**
     * Email
     *
     * Endereço de e-mail válido do usuário
     */
    email?: string | null
    /**
     * Ativo
     *
     * Indica se a conta está ativa e pode acessar o sistema
     */
    ativo?: string | null
    /**
     * Papel Id
     *
     * Papeis principal atribuído ao usuário (pode ser nulo)
     */
    papel_id?: string | null
    /**
     * Id
     *
     * Identificador único universal (UUIDv4) da entidade
     */
    id?: string | null
    /**
     * Criado Em
     *
     * Data e hora UTC da criação do registro
     */
    criado_em?: string | null
    /**
     * Atualizado Em
     *
     * Data e hora UTC da última atualização do registro (null se nunca foi atualizado)
     */
    atualizado_em?: string | null
    /**
     * Limit
     *
     * Número máximo de itens a retornar
     */
    limit?: number | null
    /**
     * Offset
     *
     * Offset absoluto para paginação (alternativa a skip)
     */
    offset?: number | null
    /**
     * Cursor
     *
     * Valor do cursor para paginação baseada em cursor
     */
    cursor?: string | null
    /**
     * Campo a ser usado como cursor (padrão: 'id')
     */
    cursor_field?: UsuariosInclude
    /**
     * Direção da paginação por cursor (next|prev)
     */
    cursor_direction?: AppSchemaPapeisFuncionalidadesSchemaCursorDirection
    /**
     * Include
     *
     * Atributos a incluir na resposta
     */
    include?: Array<UsuariosInclude>
    /**
     * Exclude
     *
     * Atributos a excluir da resposta
     */
    exclude?: Array<UsuariosInclude>
    /**
     * Expand
     *
     * Relacionamentos a expandir
     */
    expand?: Array<UsuariosExpand> | null
    /**
     * Count Only
     *
     * Retornar apenas a contagem total de itens, sem os dados
     */
    count_only?: boolean
    /**
     * Distinct
     *
     * Aplicar DISTINCT na consulta para evitar duplicatas
     */
    distinct?: boolean
    /**
     * operador da ordem do resultado (ASC | DESC)
     */
    sort_op?: AppSchemaPapeisFuncionalidadesSchemaSortOp
    /**
     * ordem do resultado (ex: criado_em)
     */
    sort_field?: UsuariosInclude
  }
  url: '/usuarios/'
}

export type LerUsuariosErrors = {
  /**
   * Erro na requisição
   */
  400: ErrorSchema
}

export type LerUsuariosError = LerUsuariosErrors[keyof LerUsuariosErrors]

export type LerUsuariosResponses = {
  /**
   * Successful Response
   */
  200: ApiSuccessGetUsuarios
}

export type LerUsuariosResponse =
  LerUsuariosResponses[keyof LerUsuariosResponses]

export type CriarUsuariosData = {
  body: PostUsuarios
  path?: never
  query?: never
  url: '/usuarios/'
}

export type CriarUsuariosErrors = {
  /**
   * Erro na requisição
   */
  400: ErrorSchema
}

export type CriarUsuariosError = CriarUsuariosErrors[keyof CriarUsuariosErrors]

export type CriarUsuariosResponses = {
  /**
   * Successful Response
   */
  201: ApiSuccessNoneType
}

export type CriarUsuariosResponse =
  CriarUsuariosResponses[keyof CriarUsuariosResponses]

export type RemoverUsuariosData = {
  body?: never
  path: {
    /**
     * Id
     *
     * ID dado a ser removido
     */
    id: string
  }
  query?: never
  url: '/usuarios/{id}'
}

export type RemoverUsuariosErrors = {
  /**
   * Erro na requisição
   */
  400: ErrorSchema
}

export type RemoverUsuariosError =
  RemoverUsuariosErrors[keyof RemoverUsuariosErrors]

export type RemoverUsuariosResponses = {
  /**
   * Successful Response
   */
  200: ApiSuccessNoneType
}

export type RemoverUsuariosResponse =
  RemoverUsuariosResponses[keyof RemoverUsuariosResponses]

export type AtualizarUsuariosData = {
  body: PatchUsuarios
  path: {
    /**
     * Id
     *
     * ID dado a ser atualizado
     */
    id: string
  }
  query?: never
  url: '/usuarios/{id}'
}

export type AtualizarUsuariosErrors = {
  /**
   * Erro na requisição
   */
  400: ErrorSchema
}

export type AtualizarUsuariosError =
  AtualizarUsuariosErrors[keyof AtualizarUsuariosErrors]

export type AtualizarUsuariosResponses = {
  /**
   * Successful Response
   */
  200: ApiSuccessNoneType
}

export type AtualizarUsuariosResponse =
  AtualizarUsuariosResponses[keyof AtualizarUsuariosResponses]

export type LerUsuariosFuncionalidadesData = {
  body?: never
  path?: never
  query?: {
    /**
     * All Data
     *
     * Retornar todas as correspondências ou apenas a primeira
     */
    all_data?: boolean
    /**
     * Usuario Id
     *
     * Chave estrangeira referenciando o ID do Usuário
     */
    usuario_id?: string | null
    /**
     * Funcionalidade Id
     *
     * Chave estrangeira referenciando o ID da Funcionalidades
     */
    funcionalidade_id?: string | null
    /**
     * Id
     *
     * Identificador único universal (UUIDv4) da entidade
     */
    id?: string | null
    /**
     * Criado Em
     *
     * Data e hora UTC da criação do registro
     */
    criado_em?: string | null
    /**
     * Atualizado Em
     *
     * Data e hora UTC da última atualização do registro (null se nunca foi atualizado)
     */
    atualizado_em?: string | null
    /**
     * Limit
     *
     * Número máximo de itens a retornar
     */
    limit?: number | null
    /**
     * Offset
     *
     * Offset absoluto para paginação (alternativa a skip)
     */
    offset?: number | null
    /**
     * Cursor
     *
     * Valor do cursor para paginação baseada em cursor
     */
    cursor?: string | null
    /**
     * Campo a ser usado como cursor (padrão: 'id')
     */
    cursor_field?: UsuariosFuncionalidadesInclude
    /**
     * Direção da paginação por cursor (next|prev)
     */
    cursor_direction?: AppSchemaPapeisFuncionalidadesSchemaCursorDirection
    /**
     * Include
     *
     * Atributos a incluir na resposta
     */
    include?: Array<UsuariosFuncionalidadesInclude>
    /**
     * Exclude
     *
     * Atributos a excluir da resposta
     */
    exclude?: Array<UsuariosFuncionalidadesInclude>
    /**
     * Expand
     *
     * Relacionamentos a expandir
     */
    expand?: Array<UsuariosFuncionalidadesExpand> | null
    /**
     * Count Only
     *
     * Retornar apenas a contagem total de itens, sem os dados
     */
    count_only?: boolean
    /**
     * Distinct
     *
     * Aplicar DISTINCT na consulta para evitar duplicatas
     */
    distinct?: boolean
    /**
     * operador da ordem do resultado (ASC | DESC)
     */
    sort_op?: AppSchemaPapeisFuncionalidadesSchemaSortOp
    /**
     * ordem do resultado (ex: criado_em)
     */
    sort_field?: UsuariosFuncionalidadesInclude
  }
  url: '/usuarios-funcionalidades/'
}

export type LerUsuariosFuncionalidadesErrors = {
  /**
   * Erro na requisição
   */
  400: ErrorSchema
}

export type LerUsuariosFuncionalidadesError =
  LerUsuariosFuncionalidadesErrors[keyof LerUsuariosFuncionalidadesErrors]

export type LerUsuariosFuncionalidadesResponses = {
  /**
   * Successful Response
   */
  200: ApiSuccessGetUsuariosFuncionalidades
}

export type LerUsuariosFuncionalidadesResponse =
  LerUsuariosFuncionalidadesResponses[keyof LerUsuariosFuncionalidadesResponses]

export type CriarUsuariosFuncionalidadesData = {
  body: PostUsuariosFuncionalidades
  path?: never
  query?: never
  url: '/usuarios-funcionalidades/'
}

export type CriarUsuariosFuncionalidadesErrors = {
  /**
   * Erro na requisição
   */
  400: ErrorSchema
}

export type CriarUsuariosFuncionalidadesError =
  CriarUsuariosFuncionalidadesErrors[keyof CriarUsuariosFuncionalidadesErrors]

export type CriarUsuariosFuncionalidadesResponses = {
  /**
   * Successful Response
   */
  201: ApiSuccessNoneType
}

export type CriarUsuariosFuncionalidadesResponse =
  CriarUsuariosFuncionalidadesResponses[keyof CriarUsuariosFuncionalidadesResponses]

export type RemoverUsuariosFuncionalidadesData = {
  body?: never
  path: {
    /**
     * Id
     *
     * ID dado a ser removido
     */
    id: string
  }
  query?: never
  url: '/usuarios-funcionalidades/{id}'
}

export type RemoverUsuariosFuncionalidadesErrors = {
  /**
   * Erro na requisição
   */
  400: ErrorSchema
}

export type RemoverUsuariosFuncionalidadesError =
  RemoverUsuariosFuncionalidadesErrors[keyof RemoverUsuariosFuncionalidadesErrors]

export type RemoverUsuariosFuncionalidadesResponses = {
  /**
   * Successful Response
   */
  200: ApiSuccessNoneType
}

export type RemoverUsuariosFuncionalidadesResponse =
  RemoverUsuariosFuncionalidadesResponses[keyof RemoverUsuariosFuncionalidadesResponses]

export type AtualizarUsuariosFuncionalidadesData = {
  body: PatchUsuariosFuncionalidades
  path: {
    /**
     * Id
     *
     * ID dado a ser atualizado
     */
    id: string
  }
  query?: never
  url: '/usuarios-funcionalidades/{id}'
}

export type AtualizarUsuariosFuncionalidadesErrors = {
  /**
   * Erro na requisição
   */
  400: ErrorSchema
}

export type AtualizarUsuariosFuncionalidadesError =
  AtualizarUsuariosFuncionalidadesErrors[keyof AtualizarUsuariosFuncionalidadesErrors]

export type AtualizarUsuariosFuncionalidadesResponses = {
  /**
   * Successful Response
   */
  200: ApiSuccessNoneType
}

export type AtualizarUsuariosFuncionalidadesResponse =
  AtualizarUsuariosFuncionalidadesResponses[keyof AtualizarUsuariosFuncionalidadesResponses]

export type LerPapeisData = {
  body?: never
  path?: never
  query?: {
    /**
     * All Data
     *
     * Retornar todas as correspondências ou apenas a primeira
     */
    all_data?: boolean
    /**
     * Nome
     *
     * Nome identificador único do papeis (ex: 'Admin', 'Gerente')
     */
    nome?: string | null
    /**
     * Ativo
     *
     * Indica se o papeis está ativo e disponível para atribuição
     */
    ativo?: string | null
    /**
     * Descricao
     *
     * Descrição detalhada das permissões e responsabilidades do papeis
     */
    descricao?: string | null
    /**
     * Id
     *
     * Identificador único universal (UUIDv4) da entidade
     */
    id?: string | null
    /**
     * Criado Em
     *
     * Data e hora UTC da criação do registro
     */
    criado_em?: string | null
    /**
     * Atualizado Em
     *
     * Data e hora UTC da última atualização do registro (null se nunca foi atualizado)
     */
    atualizado_em?: string | null
    /**
     * Limit
     *
     * Número máximo de itens a retornar
     */
    limit?: number | null
    /**
     * Offset
     *
     * Offset absoluto para paginação (alternativa a skip)
     */
    offset?: number | null
    /**
     * Cursor
     *
     * Valor do cursor para paginação baseada em cursor
     */
    cursor?: string | null
    /**
     * Campo a ser usado como cursor (padrão: 'id')
     */
    cursor_field?: PapeisInclude
    /**
     * Direção da paginação por cursor (next|prev)
     */
    cursor_direction?: AppSchemaPapeisFuncionalidadesSchemaCursorDirection
    /**
     * Include
     *
     * Atributos a incluir na resposta
     */
    include?: Array<PapeisInclude>
    /**
     * Exclude
     *
     * Atributos a excluir da resposta
     */
    exclude?: Array<PapeisInclude>
    /**
     * Count Only
     *
     * Retornar apenas a contagem total de itens, sem os dados
     */
    count_only?: boolean
    /**
     * Distinct
     *
     * Aplicar DISTINCT na consulta para evitar duplicatas
     */
    distinct?: boolean
    /**
     * operador da ordem do resultado (ASC | DESC)
     */
    sort_op?: AppSchemaPapeisFuncionalidadesSchemaSortOp
    /**
     * ordem do resultado (ex: criado_em)
     */
    sort_field?: PapeisInclude
  }
  url: '/papeis/'
}

export type LerPapeisErrors = {
  /**
   * Erro na requisição
   */
  400: ErrorSchema
}

export type LerPapeisError = LerPapeisErrors[keyof LerPapeisErrors]

export type LerPapeisResponses = {
  /**
   * Successful Response
   */
  200: ApiSuccessGetPapeis
}

export type LerPapeisResponse = LerPapeisResponses[keyof LerPapeisResponses]

export type CriarPapeisData = {
  body: PostPapeis
  path?: never
  query?: never
  url: '/papeis/'
}

export type CriarPapeisErrors = {
  /**
   * Erro na requisição
   */
  400: ErrorSchema
}

export type CriarPapeisError = CriarPapeisErrors[keyof CriarPapeisErrors]

export type CriarPapeisResponses = {
  /**
   * Successful Response
   */
  201: ApiSuccessNoneType
}

export type CriarPapeisResponse =
  CriarPapeisResponses[keyof CriarPapeisResponses]

export type RemoverPapeisData = {
  body?: never
  path: {
    /**
     * Id
     *
     * ID dado a ser removido
     */
    id: string
  }
  query?: never
  url: '/papeis/{id}'
}

export type RemoverPapeisErrors = {
  /**
   * Erro na requisição
   */
  400: ErrorSchema
}

export type RemoverPapeisError = RemoverPapeisErrors[keyof RemoverPapeisErrors]

export type RemoverPapeisResponses = {
  /**
   * Successful Response
   */
  200: ApiSuccessNoneType
}

export type RemoverPapeisResponse =
  RemoverPapeisResponses[keyof RemoverPapeisResponses]

export type AtualizarPapeisData = {
  body: PatchPapeis
  path: {
    /**
     * Id
     *
     * ID dado a ser atualizado
     */
    id: string
  }
  query?: never
  url: '/papeis/{id}'
}

export type AtualizarPapeisErrors = {
  /**
   * Erro na requisição
   */
  400: ErrorSchema
}

export type AtualizarPapeisError =
  AtualizarPapeisErrors[keyof AtualizarPapeisErrors]

export type AtualizarPapeisResponses = {
  /**
   * Successful Response
   */
  200: ApiSuccessNoneType
}

export type AtualizarPapeisResponse =
  AtualizarPapeisResponses[keyof AtualizarPapeisResponses]

export type LoginAccessTokenData = {
  body: BodyLoginAccessToken
  path?: never
  query?: never
  url: '/login/access-token'
}

export type LoginAccessTokenResponses = {
  /**
   * Successful Response
   */
  200: ResponseLoginAcessToken
}

export type LoginAccessTokenResponse =
  LoginAccessTokenResponses[keyof LoginAccessTokenResponses]

export type LoginSessionTokenData = {
  body: BodyLoginSessionToken
  path?: never
  query?: never
  url: '/login/session-token'
}

export type LoginSessionTokenResponses = {
  /**
   * Successful Response
   */
  200: ResponseLoginSessionToken
}

export type LoginSessionTokenResponse =
  LoginSessionTokenResponses[keyof LoginSessionTokenResponses]

export type EsqueciSenhaData = {
  body: EsqueciSenha
  path?: never
  query?: never
  url: '/esqueci-senha/'
}

export type EsqueciSenhaResponses = {
  /**
   * Successful Response
   */
  200: ResponseEsqueciSenha
}

export type EsqueciSenhaResponse =
  EsqueciSenhaResponses[keyof EsqueciSenhaResponses]

export type EsqueciSenhaCodigoData = {
  body?: never
  headers: {
    /**
     * Authentication
     */
    Authentication: string
  }
  path?: never
  query: {
    /**
     * Code
     */
    code: string
  }
  url: '/esqueci-senha/code'
}

export type EsqueciSenhaCodigoResponses = {
  /**
   * Successful Response
   */
  200: ResponseEsqueciSenhaCodigo
}

export type EsqueciSenhaCodigoResponse =
  EsqueciSenhaCodigoResponses[keyof EsqueciSenhaCodigoResponses]

export type NovaSenhaData = {
  body: NovaSenha
  headers: {
    /**
     * Authentication
     */
    Authentication: string
  }
  path?: never
  query?: never
  url: '/nova-senha/'
}

export type NovaSenhaResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type LerPapeisFuncionalidadesData = {
  body?: never
  path?: never
  query?: {
    /**
     * All Data
     *
     * Retornar todas as correspondências ou apenas a primeira
     */
    all_data?: boolean
    /**
     * Papel Id
     *
     * Chave estrangeira referenciando o ID do Papeis
     */
    papel_id?: string | null
    /**
     * Funcionalidade Id
     */
    funcionalidade_id?: string | null
    /**
     * Id
     *
     * Identificador único universal (UUIDv4) da entidade
     */
    id?: string | null
    /**
     * Criado Em
     *
     * Data e hora UTC da criação do registro
     */
    criado_em?: string | null
    /**
     * Atualizado Em
     *
     * Data e hora UTC da última atualização do registro (null se nunca foi atualizado)
     */
    atualizado_em?: string | null
    /**
     * Limit
     *
     * Número máximo de itens a retornar
     */
    limit?: number | null
    /**
     * Offset
     *
     * Offset absoluto para paginação (alternativa a skip)
     */
    offset?: number | null
    /**
     * Cursor
     *
     * Valor do cursor para paginação baseada em cursor
     */
    cursor?: string | null
    /**
     * Campo a ser usado como cursor (padrão: 'id')
     */
    cursor_field?: PapeisFuncionalidadesInclude
    /**
     * Direção da paginação por cursor (next|prev)
     */
    cursor_direction?: AppSchemaPapeisFuncionalidadesSchemaCursorDirection
    /**
     * Include
     *
     * Atributos a incluir na resposta
     */
    include?: Array<PapeisFuncionalidadesInclude>
    /**
     * Exclude
     *
     * Atributos a excluir da resposta
     */
    exclude?: Array<PapeisFuncionalidadesInclude>
    /**
     * Expand
     *
     * Relacionamentos a expandir
     */
    expand?: Array<PapeisFuncionalidadesExpand> | null
    /**
     * Count Only
     *
     * Retornar apenas a contagem total de itens, sem os dados
     */
    count_only?: boolean
    /**
     * Distinct
     *
     * Aplicar DISTINCT na consulta para evitar duplicatas
     */
    distinct?: boolean
    /**
     * operador da ordem do resultado (ASC | DESC)
     */
    sort_op?: AppSchemaPapeisFuncionalidadesSchemaSortOp
    /**
     * ordem do resultado (ex: criado_em)
     */
    sort_field?: PapeisFuncionalidadesInclude
  }
  url: '/papeis-funcionalidades/'
}

export type LerPapeisFuncionalidadesErrors = {
  /**
   * Erro na requisição
   */
  400: ErrorSchema
}

export type LerPapeisFuncionalidadesError =
  LerPapeisFuncionalidadesErrors[keyof LerPapeisFuncionalidadesErrors]

export type LerPapeisFuncionalidadesResponses = {
  /**
   * Successful Response
   */
  200: ApiSuccessGetPapeisFuncionalidades
}

export type LerPapeisFuncionalidadesResponse =
  LerPapeisFuncionalidadesResponses[keyof LerPapeisFuncionalidadesResponses]

export type CriarPapeisFuncionalidadesData = {
  body: PostPapeisFuncionalidades
  path?: never
  query?: never
  url: '/papeis-funcionalidades/'
}

export type CriarPapeisFuncionalidadesErrors = {
  /**
   * Erro na requisição
   */
  400: ErrorSchema
}

export type CriarPapeisFuncionalidadesError =
  CriarPapeisFuncionalidadesErrors[keyof CriarPapeisFuncionalidadesErrors]

export type CriarPapeisFuncionalidadesResponses = {
  /**
   * Successful Response
   */
  201: ApiSuccessNoneType
}

export type CriarPapeisFuncionalidadesResponse =
  CriarPapeisFuncionalidadesResponses[keyof CriarPapeisFuncionalidadesResponses]

export type RemoverPapeisFuncionalidadesData = {
  body?: never
  path: {
    /**
     * Id
     *
     * ID dado a ser removido
     */
    id: string
  }
  query?: never
  url: '/papeis-funcionalidades/{id}'
}

export type RemoverPapeisFuncionalidadesErrors = {
  /**
   * Erro na requisição
   */
  400: ErrorSchema
}

export type RemoverPapeisFuncionalidadesError =
  RemoverPapeisFuncionalidadesErrors[keyof RemoverPapeisFuncionalidadesErrors]

export type RemoverPapeisFuncionalidadesResponses = {
  /**
   * Successful Response
   */
  200: ApiSuccessNoneType
}

export type RemoverPapeisFuncionalidadesResponse =
  RemoverPapeisFuncionalidadesResponses[keyof RemoverPapeisFuncionalidadesResponses]

export type AtualizarPapeisFuncionalidadesData = {
  body: PatchPapeisFuncionalidades
  path: {
    /**
     * Id
     *
     * ID dado a ser atualizado
     */
    id: string
  }
  query?: never
  url: '/papeis-funcionalidades/{id}'
}

export type AtualizarPapeisFuncionalidadesErrors = {
  /**
   * Erro na requisição
   */
  400: ErrorSchema
}

export type AtualizarPapeisFuncionalidadesError =
  AtualizarPapeisFuncionalidadesErrors[keyof AtualizarPapeisFuncionalidadesErrors]

export type AtualizarPapeisFuncionalidadesResponses = {
  /**
   * Successful Response
   */
  200: ApiSuccessNoneType
}

export type AtualizarPapeisFuncionalidadesResponse =
  AtualizarPapeisFuncionalidadesResponses[keyof AtualizarPapeisFuncionalidadesResponses]
