// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod'

/**
 * SortOp
 */
export const zAppSchemaPapeisFuncionalidadesSchemaSortOp = z.enum([
  'ASC',
  'DESC',
])

/**
 * CursorDirection
 */
export const zAppSchemaPapeisFuncionalidadesSchemaCursorDirection = z.enum([
  'next',
  'prev',
])

/**
 * UsuariosInclude
 */
export const zUsuariosInclude = z.enum([
  'nome_usuario',
  'nome_completo',
  'telefone',
  'email',
  'ativo',
  'papel_id',
  'id',
  'criado_em',
  'atualizado_em',
])

/**
 * UsuariosFuncionalidadesInclude
 */
export const zUsuariosFuncionalidadesInclude = z.enum([
  'usuario_id',
  'funcionalidade_id',
  'id',
  'criado_em',
  'atualizado_em',
])

/**
 * UsuariosFuncionalidadesExpand
 */
export const zUsuariosFuncionalidadesExpand = z.enum([
  'funcionalidades',
  'usuarios',
])

/**
 * UsuariosExpand
 */
export const zUsuariosExpand = z.enum(['papeis', 'usuarios_funcionalidades'])

/**
 * TenantsInclude
 */
export const zTenantsInclude = z.enum([
  'nome',
  'slug',
  'schema_criado',
  'ativo',
  'configuracao',
  'id',
  'criado_em',
  'atualizado_em',
])

/**
 * GetFuncionalidades
 */
export const zGetFuncionalidades = z.object({
  chave: z.optional(z.union([z.int(), z.null()])),
  nome: z.optional(z.string()),
  escopo: z.optional(z.string()),
  caminho: z.optional(z.string()),
  metodo: z.optional(z.string()),
  descricao: z.optional(z.union([z.string(), z.null()])),
  categoria: z.optional(z.union([z.string(), z.null()])),
  sensivel: z.optional(z.union([z.boolean(), z.null()])),
  versao: z.optional(z.union([z.int(), z.null()])),
  id: z.optional(z.uuid()),
  criado_em: z.optional(z.iso.datetime()),
  atualizado_em: z.optional(z.union([z.iso.datetime(), z.null()])),
})

/**
 * GetUsuariosFuncionalidades
 */
export const zGetUsuariosFuncionalidades = z.object({
  usuario_id: z.optional(z.uuid()),
  funcionalidade_id: z.optional(z.uuid()),
  id: z.optional(z.uuid()),
  criado_em: z.optional(z.iso.datetime()),
  atualizado_em: z.optional(z.union([z.iso.datetime(), z.null()])),
  funcionalidades: z.optional(z.union([zGetFuncionalidades, z.null()])),
})

/**
 * GetPapeis
 */
export const zGetPapeis = z.object({
  nome: z.optional(z.string()),
  ativo: z.optional(z.boolean()),
  descricao: z.optional(z.union([z.string(), z.null()])),
  id: z.optional(z.uuid()),
  criado_em: z.optional(z.iso.datetime()),
  atualizado_em: z.optional(z.union([z.iso.datetime(), z.null()])),
})

/**
 * GetUsuarios
 */
export const zGetUsuarios = z.object({
  nome_usuario: z.optional(z.string()),
  nome_completo: z.optional(z.union([z.string(), z.null()])),
  telefone: z.optional(z.union([z.string(), z.null()])),
  email: z.optional(z.string()),
  ativo: z.optional(z.boolean()),
  papel_id: z.optional(z.union([z.uuid(), z.null()])),
  id: z.optional(z.uuid()),
  criado_em: z.optional(z.iso.datetime()),
  atualizado_em: z.optional(z.union([z.iso.datetime(), z.null()])),
  papeis: z.optional(z.union([zGetPapeis, z.null()])),
  usuarios_funcionalidades: z.optional(
    z.array(z.union([zGetUsuariosFuncionalidades, z.null()]))
  ),
})

/**
 * ResponseLoginSessionToken
 */
export const zResponseLoginSessionToken = z.object({
  user: zGetUsuarios,
})

/**
 * ResponseLoginAcessToken
 */
export const zResponseLoginAcessToken = z.object({
  access_token: z.string(),
  token_type: z.string(),
  permission: z.union([z.array(z.string()), z.null()]),
  user: zGetUsuarios,
  papel: z.string(),
})

/**
 * ResponseEsqueciSenhaCodigo
 */
export const zResponseEsqueciSenhaCodigo = z.object({
  token: z.string(),
})

/**
 * ResponseEsqueciSenha
 */
export const zResponseEsqueciSenha = z.object({
  token: z.string(),
})

/**
 * PostUsuariosFuncionalidades
 */
export const zPostUsuariosFuncionalidades = z.object({
  usuario_id: z.uuid(),
  funcionalidade_id: z.uuid(),
})

/**
 * PostUsuarios
 */
export const zPostUsuarios = z.object({
  nome_usuario: z.string(),
  nome_completo: z.optional(z.union([z.string(), z.null()])),
  telefone: z.optional(z.union([z.string(), z.null()])),
  email: z.string(),
  senha: z.string(),
  ativo: z.optional(z.boolean()).default(true),
  papel_id: z.optional(z.union([z.uuid(), z.null()])),
})

/**
 * PostTenants
 */
export const zPostTenants = z.object({
  nome: z.string(),
  slug: z.string(),
  schema_criado: z.optional(z.boolean()).default(false),
  ativo: z.optional(z.boolean()).default(true),
  configuracao: z.optional(
    z.union([z.record(z.string(), z.unknown()), z.null()])
  ),
})

/**
 * PostPapeisFuncionalidades
 */
export const zPostPapeisFuncionalidades = z.object({
  papel_id: z.uuid(),
  funcionalidade_id: z.uuid(),
})

/**
 * PostPapeis
 */
export const zPostPapeis = z.object({
  nome: z.string(),
  ativo: z.optional(z.boolean()).default(true),
  descricao: z.optional(z.union([z.string(), z.null()])),
})

/**
 * PostFuncionalidades
 */
export const zPostFuncionalidades = z.object({
  nome: z.string(),
  escopo: z.string(),
  caminho: z.string(),
  metodo: z.string(),
  descricao: z.optional(z.union([z.string(), z.null()])),
  categoria: z.optional(z.union([z.string(), z.null()])),
  sensivel: z.optional(z.union([z.boolean(), z.null()])).default(false),
  versao: z.optional(z.union([z.int(), z.null()])).default(1),
})

/**
 * PatchUsuariosFuncionalidades
 */
export const zPatchUsuariosFuncionalidades = z.object({
  usuario_id: z.optional(z.union([z.uuid(), z.null()])),
  funcionalidade_id: z.optional(z.union([z.uuid(), z.null()])),
})

/**
 * PatchUsuarios
 */
export const zPatchUsuarios = z.object({
  nome_usuario: z.optional(z.union([z.string(), z.null()])),
  nome_completo: z.optional(z.union([z.string(), z.null()])),
  telefone: z.optional(z.union([z.string(), z.null()])),
  email: z.optional(z.union([z.string(), z.null()])),
  senha: z.optional(z.union([z.string(), z.null()])),
  ativo: z.optional(z.union([z.boolean(), z.null()])),
  papel_id: z.optional(z.union([z.uuid(), z.null()])),
})

/**
 * PatchTenants
 */
export const zPatchTenants = z.object({
  nome: z.optional(z.union([z.string(), z.null()])),
  slug: z.optional(z.union([z.string(), z.null()])),
  schema_criado: z.optional(z.union([z.boolean(), z.null()])),
  ativo: z.optional(z.union([z.boolean(), z.null()])),
  configuracao: z.optional(
    z.union([z.record(z.string(), z.unknown()), z.null()])
  ),
})

/**
 * PatchPapeisFuncionalidades
 */
export const zPatchPapeisFuncionalidades = z.object({
  papel_id: z.optional(z.union([z.uuid(), z.null()])),
  funcionalidade_id: z.optional(z.union([z.uuid(), z.null()])),
})

/**
 * PatchPapeis
 */
export const zPatchPapeis = z.object({
  nome: z.optional(z.union([z.string(), z.null()])),
  ativo: z.optional(z.union([z.boolean(), z.null()])),
  descricao: z.optional(z.union([z.string(), z.null()])),
})

/**
 * PatchFuncionalidades
 */
export const zPatchFuncionalidades = z.object({
  nome: z.optional(z.union([z.string(), z.null()])),
  escopo: z.optional(z.union([z.string(), z.null()])),
  caminho: z.optional(z.union([z.string(), z.null()])),
  metodo: z.optional(z.union([z.string(), z.null()])),
  descricao: z.optional(z.union([z.string(), z.null()])),
  categoria: z.optional(z.union([z.string(), z.null()])),
  sensivel: z.optional(z.union([z.boolean(), z.null()])),
  versao: z.optional(z.union([z.int(), z.null()])),
})

/**
 * PapeisInclude
 */
export const zPapeisInclude = z.enum([
  'nome',
  'ativo',
  'descricao',
  'id',
  'criado_em',
  'atualizado_em',
])

/**
 * PapeisFuncionalidadesInclude
 */
export const zPapeisFuncionalidadesInclude = z.enum([
  'papel_id',
  'funcionalidade_id',
  'id',
  'criado_em',
  'atualizado_em',
])

/**
 * PapeisFuncionalidadesExpand
 */
export const zPapeisFuncionalidadesExpand = z.enum([
  'funcionalidades',
  'papeis',
])

/**
 * NovaSenha
 */
export const zNovaSenha = z.object({
  senha: z.string(),
})

/**
 * Meta
 *
 * Metadados para operações
 */
export const zMeta = z.object({
  total_items: z.optional(z.int()).default(0),
  total_query: z.optional(z.int()).default(0),
  items_per_page: z.optional(z.union([z.int(), z.null()])).default(10),
  current_page: z.optional(z.union([z.int(), z.null()])),
  total_pages: z.optional(z.union([z.int(), z.null()])),
  next_cursor: z.optional(z.union([z.string(), z.null()])),
  prev_cursor: z.optional(z.union([z.string(), z.null()])),
  next_offset: z.optional(z.union([z.int(), z.null()])),
  prev_offset: z.optional(z.union([z.int(), z.null()])),
  has_next: z.optional(z.union([z.boolean(), z.null()])),
  has_prev: z.optional(z.union([z.boolean(), z.null()])),
})

/**
 * GetTenants
 */
export const zGetTenants = z.object({
  nome: z.optional(z.string()),
  slug: z.optional(z.string()),
  schema_criado: z.optional(z.boolean()),
  ativo: z.optional(z.boolean()),
  configuracao: z.optional(
    z.union([z.record(z.string(), z.unknown()), z.null()])
  ),
  id: z.optional(z.uuid()),
  criado_em: z.optional(z.iso.datetime()),
  atualizado_em: z.optional(z.union([z.iso.datetime(), z.null()])),
})

/**
 * GetPapeisFuncionalidades
 */
export const zGetPapeisFuncionalidades = z.object({
  papel_id: z.optional(z.uuid()),
  funcionalidade_id: z.optional(z.uuid()),
  id: z.optional(z.uuid()),
  criado_em: z.optional(z.iso.datetime()),
  atualizado_em: z.optional(z.union([z.iso.datetime(), z.null()])),
  funcionalidades: z.optional(z.union([zGetFuncionalidades, z.null()])),
  papeis: z.optional(z.union([zGetPapeis, z.null()])),
})

/**
 * FuncionalidadesInclude
 */
export const zFuncionalidadesInclude = z.enum([
  'chave',
  'nome',
  'escopo',
  'caminho',
  'metodo',
  'descricao',
  'categoria',
  'sensivel',
  'versao',
  'id',
  'criado_em',
  'atualizado_em',
])

/**
 * EsqueciSenha
 */
export const zEsqueciSenha = z.object({
  email: z.string(),
})

/**
 * Detail
 */
export const zDetail = z.object({
  loc: z
    .optional(z.union([z.array(z.union([z.string(), z.int()])), z.null()]))
    .default(['global']),
  msg: z.string(),
  type: z.optional(z.union([z.string(), z.null()])),
  debug: z.optional(z.union([z.string(), z.null()])),
})

/**
 * ErrorSchema
 */
export const zErrorSchema = z.object({
  detail: z.array(zDetail),
})

/**
 * Body_login_session_token
 */
export const zBodyLoginSessionToken = z.object({
  username: z.string(),
  password: z.string(),
})

/**
 * Body_login_access_token
 */
export const zBodyLoginAccessToken = z.object({
  username: z.string(),
  password: z.string(),
})

/**
 * ApiSuccess[NoneType]
 */
export const zApiSuccessNoneType = z.object({
  msg: z.optional(z.union([z.string(), z.null()])).default('Success'),
  meta: z.optional(z.union([zMeta, z.null()])),
  data: z.optional(z.union([z.array(z.null()), z.null()])),
})

/**
 * ApiSuccess[GetUsuarios]
 */
export const zApiSuccessGetUsuarios = z.object({
  msg: z.optional(z.union([z.string(), z.null()])).default('Success'),
  meta: z.optional(z.union([zMeta, z.null()])),
  data: z.optional(z.union([z.array(zGetUsuarios), z.null()])),
})

/**
 * ApiSuccess[GetUsuariosFuncionalidades]
 */
export const zApiSuccessGetUsuariosFuncionalidades = z.object({
  msg: z.optional(z.union([z.string(), z.null()])).default('Success'),
  meta: z.optional(z.union([zMeta, z.null()])),
  data: z.optional(z.union([z.array(zGetUsuariosFuncionalidades), z.null()])),
})

/**
 * ApiSuccess[GetTenants]
 */
export const zApiSuccessGetTenants = z.object({
  msg: z.optional(z.union([z.string(), z.null()])).default('Success'),
  meta: z.optional(z.union([zMeta, z.null()])),
  data: z.optional(z.union([z.array(zGetTenants), z.null()])),
})

/**
 * ApiSuccess[GetPapeis]
 */
export const zApiSuccessGetPapeis = z.object({
  msg: z.optional(z.union([z.string(), z.null()])).default('Success'),
  meta: z.optional(z.union([zMeta, z.null()])),
  data: z.optional(z.union([z.array(zGetPapeis), z.null()])),
})

/**
 * ApiSuccess[GetPapeisFuncionalidades]
 */
export const zApiSuccessGetPapeisFuncionalidades = z.object({
  msg: z.optional(z.union([z.string(), z.null()])).default('Success'),
  meta: z.optional(z.union([zMeta, z.null()])),
  data: z.optional(z.union([z.array(zGetPapeisFuncionalidades), z.null()])),
})

/**
 * ApiSuccess[GetFuncionalidades]
 */
export const zApiSuccessGetFuncionalidades = z.object({
  msg: z.optional(z.union([z.string(), z.null()])).default('Success'),
  meta: z.optional(z.union([zMeta, z.null()])),
  data: z.optional(z.union([z.array(zGetFuncionalidades), z.null()])),
})

export const zLerFuncionalidadesData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      all_data: z.optional(z.boolean()).default(true),
      chave: z.optional(z.union([z.string(), z.null()])),
      nome: z.optional(z.union([z.string(), z.null()])),
      escopo: z.optional(z.union([z.string(), z.null()])),
      caminho: z.optional(z.union([z.string(), z.null()])),
      metodo: z.optional(z.union([z.string(), z.null()])),
      descricao: z.optional(z.union([z.string(), z.null()])),
      categoria: z.optional(z.union([z.string(), z.null()])),
      sensivel: z.optional(z.union([z.string(), z.null()])),
      versao: z.optional(z.union([z.string(), z.null()])),
      id: z.optional(z.union([z.string(), z.null()])),
      criado_em: z.optional(z.union([z.string(), z.null()])),
      atualizado_em: z.optional(z.union([z.string(), z.null()])),
      limit: z.optional(z.union([z.int(), z.null()])),
      offset: z.optional(z.union([z.int(), z.null()])),
      cursor: z.optional(z.union([z.string(), z.null()])),
      cursor_field: z.optional(zFuncionalidadesInclude).default('id'),
      cursor_direction: z
        .optional(zAppSchemaPapeisFuncionalidadesSchemaCursorDirection)
        .default('next'),
      include: z.optional(z.array(zFuncionalidadesInclude)).default([]),
      exclude: z.optional(z.array(zFuncionalidadesInclude)).default([]),
      count_only: z.optional(z.boolean()).default(false),
      distinct: z.optional(z.boolean()).default(false),
      sort_op: z.optional(zAppSchemaPapeisFuncionalidadesSchemaSortOp),
      sort_field: z.optional(zFuncionalidadesInclude),
    })
  ),
})

/**
 * Successful Response
 */
export const zLerFuncionalidadesResponse = zApiSuccessGetFuncionalidades

export const zCriarFuncionalidadesData = z.object({
  body: zPostFuncionalidades,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zCriarFuncionalidadesResponse = zApiSuccessNoneType

export const zRemoverFuncionalidadesData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zRemoverFuncionalidadesResponse = zApiSuccessNoneType

export const zAtualizarFuncionalidadesData = z.object({
  body: zPatchFuncionalidades,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zAtualizarFuncionalidadesResponse = zApiSuccessNoneType

export const zLerTenantsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      all_data: z.optional(z.boolean()).default(true),
      nome: z.optional(z.union([z.string(), z.null()])),
      slug: z.optional(z.union([z.string(), z.null()])),
      schema_criado: z.optional(z.union([z.string(), z.null()])),
      ativo: z.optional(z.union([z.string(), z.null()])),
      configuracao: z.optional(z.union([z.string(), z.null()])),
      id: z.optional(z.union([z.string(), z.null()])),
      criado_em: z.optional(z.union([z.string(), z.null()])),
      atualizado_em: z.optional(z.union([z.string(), z.null()])),
      limit: z.optional(z.union([z.int(), z.null()])),
      offset: z.optional(z.union([z.int(), z.null()])),
      cursor: z.optional(z.union([z.string(), z.null()])),
      cursor_field: z.optional(zTenantsInclude).default('id'),
      cursor_direction: z
        .optional(zAppSchemaPapeisFuncionalidadesSchemaCursorDirection)
        .default('next'),
      include: z.optional(z.array(zTenantsInclude)).default([]),
      exclude: z.optional(z.array(zTenantsInclude)).default([]),
      count_only: z.optional(z.boolean()).default(false),
      distinct: z.optional(z.boolean()).default(false),
      sort_op: z.optional(zAppSchemaPapeisFuncionalidadesSchemaSortOp),
      sort_field: z.optional(zTenantsInclude),
    })
  ),
})

/**
 * Successful Response
 */
export const zLerTenantsResponse = zApiSuccessGetTenants

export const zCriarTenantsData = z.object({
  body: zPostTenants,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zCriarTenantsResponse = zApiSuccessNoneType

export const zRemoverTenantsData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zRemoverTenantsResponse = zApiSuccessNoneType

export const zAtualizarTenantsData = z.object({
  body: zPatchTenants,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zAtualizarTenantsResponse = zApiSuccessNoneType

export const zLerUsuariosData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      all_data: z.optional(z.boolean()).default(true),
      nome_usuario: z.optional(z.union([z.string(), z.null()])),
      nome_completo: z.optional(z.union([z.string(), z.null()])),
      telefone: z.optional(z.union([z.string(), z.null()])),
      email: z.optional(z.union([z.string(), z.null()])),
      ativo: z.optional(z.union([z.string(), z.null()])),
      papel_id: z.optional(z.union([z.string(), z.null()])),
      id: z.optional(z.union([z.string(), z.null()])),
      criado_em: z.optional(z.union([z.string(), z.null()])),
      atualizado_em: z.optional(z.union([z.string(), z.null()])),
      limit: z.optional(z.union([z.int(), z.null()])),
      offset: z.optional(z.union([z.int(), z.null()])),
      cursor: z.optional(z.union([z.string(), z.null()])),
      cursor_field: z.optional(zUsuariosInclude).default('id'),
      cursor_direction: z
        .optional(zAppSchemaPapeisFuncionalidadesSchemaCursorDirection)
        .default('next'),
      include: z.optional(z.array(zUsuariosInclude)).default([]),
      exclude: z.optional(z.array(zUsuariosInclude)).default([]),
      expand: z.optional(z.union([z.array(zUsuariosExpand), z.null()])),
      count_only: z.optional(z.boolean()).default(false),
      distinct: z.optional(z.boolean()).default(false),
      sort_op: z.optional(zAppSchemaPapeisFuncionalidadesSchemaSortOp),
      sort_field: z.optional(zUsuariosInclude),
    })
  ),
})

/**
 * Successful Response
 */
export const zLerUsuariosResponse = zApiSuccessGetUsuarios

export const zCriarUsuariosData = z.object({
  body: zPostUsuarios,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zCriarUsuariosResponse = zApiSuccessNoneType

export const zRemoverUsuariosData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zRemoverUsuariosResponse = zApiSuccessNoneType

export const zAtualizarUsuariosData = z.object({
  body: zPatchUsuarios,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zAtualizarUsuariosResponse = zApiSuccessNoneType

export const zLerUsuariosFuncionalidadesData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      all_data: z.optional(z.boolean()).default(true),
      usuario_id: z.optional(z.union([z.string(), z.null()])),
      funcionalidade_id: z.optional(z.union([z.string(), z.null()])),
      id: z.optional(z.union([z.string(), z.null()])),
      criado_em: z.optional(z.union([z.string(), z.null()])),
      atualizado_em: z.optional(z.union([z.string(), z.null()])),
      limit: z.optional(z.union([z.int(), z.null()])),
      offset: z.optional(z.union([z.int(), z.null()])),
      cursor: z.optional(z.union([z.string(), z.null()])),
      cursor_field: z.optional(zUsuariosFuncionalidadesInclude).default('id'),
      cursor_direction: z
        .optional(zAppSchemaPapeisFuncionalidadesSchemaCursorDirection)
        .default('next'),
      include: z.optional(z.array(zUsuariosFuncionalidadesInclude)).default([]),
      exclude: z.optional(z.array(zUsuariosFuncionalidadesInclude)).default([]),
      expand: z.optional(
        z.union([z.array(zUsuariosFuncionalidadesExpand), z.null()])
      ),
      count_only: z.optional(z.boolean()).default(false),
      distinct: z.optional(z.boolean()).default(false),
      sort_op: z.optional(zAppSchemaPapeisFuncionalidadesSchemaSortOp),
      sort_field: z.optional(zUsuariosFuncionalidadesInclude),
    })
  ),
})

/**
 * Successful Response
 */
export const zLerUsuariosFuncionalidadesResponse =
  zApiSuccessGetUsuariosFuncionalidades

export const zCriarUsuariosFuncionalidadesData = z.object({
  body: zPostUsuariosFuncionalidades,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zCriarUsuariosFuncionalidadesResponse = zApiSuccessNoneType

export const zRemoverUsuariosFuncionalidadesData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zRemoverUsuariosFuncionalidadesResponse = zApiSuccessNoneType

export const zAtualizarUsuariosFuncionalidadesData = z.object({
  body: zPatchUsuariosFuncionalidades,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zAtualizarUsuariosFuncionalidadesResponse = zApiSuccessNoneType

export const zLerPapeisData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      all_data: z.optional(z.boolean()).default(true),
      nome: z.optional(z.union([z.string(), z.null()])),
      ativo: z.optional(z.union([z.string(), z.null()])),
      descricao: z.optional(z.union([z.string(), z.null()])),
      id: z.optional(z.union([z.string(), z.null()])),
      criado_em: z.optional(z.union([z.string(), z.null()])),
      atualizado_em: z.optional(z.union([z.string(), z.null()])),
      limit: z.optional(z.union([z.int(), z.null()])),
      offset: z.optional(z.union([z.int(), z.null()])),
      cursor: z.optional(z.union([z.string(), z.null()])),
      cursor_field: z.optional(zPapeisInclude).default('id'),
      cursor_direction: z
        .optional(zAppSchemaPapeisFuncionalidadesSchemaCursorDirection)
        .default('next'),
      include: z.optional(z.array(zPapeisInclude)).default([]),
      exclude: z.optional(z.array(zPapeisInclude)).default([]),
      count_only: z.optional(z.boolean()).default(false),
      distinct: z.optional(z.boolean()).default(false),
      sort_op: z.optional(zAppSchemaPapeisFuncionalidadesSchemaSortOp),
      sort_field: z.optional(zPapeisInclude),
    })
  ),
})

/**
 * Successful Response
 */
export const zLerPapeisResponse = zApiSuccessGetPapeis

export const zCriarPapeisData = z.object({
  body: zPostPapeis,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zCriarPapeisResponse = zApiSuccessNoneType

export const zRemoverPapeisData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zRemoverPapeisResponse = zApiSuccessNoneType

export const zAtualizarPapeisData = z.object({
  body: zPatchPapeis,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zAtualizarPapeisResponse = zApiSuccessNoneType

export const zLoginAccessTokenData = z.object({
  body: zBodyLoginAccessToken,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zLoginAccessTokenResponse = zResponseLoginAcessToken

export const zLoginSessionTokenData = z.object({
  body: zBodyLoginSessionToken,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zLoginSessionTokenResponse = zResponseLoginSessionToken

export const zEsqueciSenhaData = z.object({
  body: zEsqueciSenha,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zEsqueciSenhaResponse = zResponseEsqueciSenha

export const zEsqueciSenhaCodigoData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.object({
    code: z.string(),
  }),
  headers: z.object({
    Authentication: z.string(),
  }),
})

/**
 * Successful Response
 */
export const zEsqueciSenhaCodigoResponse = zResponseEsqueciSenhaCodigo

export const zNovaSenhaData = z.object({
  body: zNovaSenha,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
  headers: z.object({
    Authentication: z.string(),
  }),
})

export const zLerPapeisFuncionalidadesData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      all_data: z.optional(z.boolean()).default(true),
      papel_id: z.optional(z.union([z.string(), z.null()])),
      funcionalidade_id: z.optional(z.union([z.string(), z.null()])),
      id: z.optional(z.union([z.string(), z.null()])),
      criado_em: z.optional(z.union([z.string(), z.null()])),
      atualizado_em: z.optional(z.union([z.string(), z.null()])),
      limit: z.optional(z.union([z.int(), z.null()])),
      offset: z.optional(z.union([z.int(), z.null()])),
      cursor: z.optional(z.union([z.string(), z.null()])),
      cursor_field: z.optional(zPapeisFuncionalidadesInclude).default('id'),
      cursor_direction: z
        .optional(zAppSchemaPapeisFuncionalidadesSchemaCursorDirection)
        .default('next'),
      include: z.optional(z.array(zPapeisFuncionalidadesInclude)).default([]),
      exclude: z.optional(z.array(zPapeisFuncionalidadesInclude)).default([]),
      expand: z.optional(
        z.union([z.array(zPapeisFuncionalidadesExpand), z.null()])
      ),
      count_only: z.optional(z.boolean()).default(false),
      distinct: z.optional(z.boolean()).default(false),
      sort_op: z.optional(zAppSchemaPapeisFuncionalidadesSchemaSortOp),
      sort_field: z.optional(zPapeisFuncionalidadesInclude),
    })
  ),
})

/**
 * Successful Response
 */
export const zLerPapeisFuncionalidadesResponse =
  zApiSuccessGetPapeisFuncionalidades

export const zCriarPapeisFuncionalidadesData = z.object({
  body: zPostPapeisFuncionalidades,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zCriarPapeisFuncionalidadesResponse = zApiSuccessNoneType

export const zRemoverPapeisFuncionalidadesData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zRemoverPapeisFuncionalidadesResponse = zApiSuccessNoneType

export const zAtualizarPapeisFuncionalidadesData = z.object({
  body: zPatchPapeisFuncionalidades,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zAtualizarPapeisFuncionalidadesResponse = zApiSuccessNoneType
