// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod'

/**
 * GetPlanos
 */
export const zGetPlanos = z.object({
  nome: z.optional(z.string()),
  descricao: z.optional(z.union([z.string(), z.null()])),
  preco: z.optional(z.number()),
  ativo: z.optional(z.boolean()),
  max_usuarios: z.optional(z.int()),
  max_analises: z.optional(z.int()),
  recursos: z.optional(z.union([z.record(z.string(), z.unknown()), z.null()])),
  id: z.optional(z.uuid()),
  criado_em: z.optional(z.iso.datetime()),
  atualizado_em: z.optional(z.union([z.iso.datetime(), z.null()])),
})

/**
 * GetEmpresas
 */
export const zGetEmpresas = z.object({
  nome: z.optional(z.string()),
  nome_fantasia: z.optional(z.union([z.string(), z.null()])),
  cnpj: z.optional(z.union([z.string(), z.null()])),
  segmento: z.optional(z.union([z.string(), z.null()])),
  email: z.optional(z.union([z.string(), z.null()])),
  telefone: z.optional(z.union([z.string(), z.null()])),
  celular: z.optional(z.union([z.string(), z.null()])),
  cep: z.optional(z.union([z.string(), z.null()])),
  endereco: z.optional(z.union([z.string(), z.null()])),
  numero: z.optional(z.union([z.string(), z.null()])),
  complemento: z.optional(z.union([z.string(), z.null()])),
  bairro: z.optional(z.union([z.string(), z.null()])),
  cidade: z.optional(z.union([z.string(), z.null()])),
  estado: z.optional(z.union([z.string(), z.null()])),
  ativo: z.optional(z.boolean()),
  data_ativacao: z.optional(z.union([z.iso.datetime(), z.null()])),
  data_desativacao: z.optional(z.union([z.iso.datetime(), z.null()])),
  dominio: z.optional(z.union([z.string(), z.null()])),
  subdominio: z.optional(z.union([z.string(), z.null()])),
  plano_id: z.optional(z.uuid()),
  plano_nome: z.optional(z.union([z.string(), z.null()])),
  valor_contrato: z.optional(z.union([z.number(), z.null()])),
  ciclo_cobranca: z.optional(z.string()),
  max_usuarios: z.optional(z.int()),
  max_analises: z.optional(z.int()),
  configuracao: z.optional(
    z.union([z.record(z.string(), z.unknown()), z.null()])
  ),
  id: z.optional(z.uuid()),
  criado_em: z.optional(z.iso.datetime()),
  atualizado_em: z.optional(z.union([z.iso.datetime(), z.null()])),
  plano: z.optional(z.union([zGetPlanos, z.null()])),
})

/**
 * GetPapeis
 */
export const zGetPapeis = z.object({
  nome: z.optional(z.union([z.string(), z.null()])),
  ativo: z.optional(z.union([z.boolean(), z.null()])),
  descricao: z.optional(z.union([z.string(), z.null()])),
  id: z.optional(z.uuid()),
  criado_em: z.optional(z.union([z.iso.datetime(), z.null()])),
  atualizado_em: z.optional(z.union([z.iso.datetime(), z.null()])),
})

/**
 * GetFuncionalidades
 */
export const zGetFuncionalidades = z.object({
  chave: z.optional(z.union([z.int(), z.null()])),
  nome: z.optional(z.union([z.string(), z.null()])),
  escopo: z.optional(z.union([z.string(), z.null()])),
  caminho: z.optional(z.union([z.string(), z.null()])),
  metodo: z.optional(z.union([z.string(), z.null()])),
  descricao: z.optional(z.union([z.string(), z.null()])),
  categoria: z.optional(z.union([z.string(), z.null()])),
  sensivel: z.optional(z.union([z.boolean(), z.null()])),
  versao: z.optional(z.union([z.int(), z.null()])),
  id: z.optional(z.uuid()),
  criado_em: z.optional(z.union([z.iso.datetime(), z.null()])),
  atualizado_em: z.optional(z.union([z.iso.datetime(), z.null()])),
})

/**
 * GetUsuariosFuncionalidades
 */
export const zGetUsuariosFuncionalidades = z.object({
  usuario_id: z.optional(z.union([z.uuid(), z.null()])),
  funcionalidade_id: z.optional(z.union([z.uuid(), z.null()])),
  id: z.optional(z.uuid()),
  criado_em: z.optional(z.union([z.iso.datetime(), z.null()])),
  atualizado_em: z.optional(z.union([z.iso.datetime(), z.null()])),
  funcionalidades: z.optional(z.union([zGetFuncionalidades, z.null()])),
})

/**
 * GetEquipes
 */
export const zAppSchemaEquipeUsuariosSchemaGetEquipes = z.object({
  nome: z.optional(z.union([z.string(), z.null()])),
  descricao: z.optional(z.union([z.string(), z.null()])),
  usuario_id: z.optional(z.union([z.uuid(), z.null()])),
  status: z.optional(z.union([z.boolean(), z.null()])),
  id: z.optional(z.uuid()),
  criado_em: z.optional(z.union([z.iso.datetime(), z.null()])),
  atualizado_em: z.optional(z.union([z.iso.datetime(), z.null()])),
})

/**
 * GetUsuarios
 */
export const zAppSchemaEquipeUsuariosSchemaGetUsuarios = z.object({
  nome_usuario: z.optional(z.union([z.string(), z.null()])),
  nome_completo: z.optional(z.union([z.string(), z.null()])),
  nivel: z.optional(z.union([z.string(), z.null()])),
  empresa: z.optional(z.union([z.string(), z.null()])),
  telefone: z.optional(z.union([z.string(), z.null()])),
  email: z.optional(z.union([z.string(), z.null()])),
  ativo: z.optional(z.union([z.boolean(), z.null()])),
  papel: z.optional(z.union([z.string(), z.null()])),
  papel_id: z.optional(z.union([z.uuid(), z.null()])),
  id: z.optional(z.uuid()),
  criado_em: z.optional(z.union([z.iso.datetime(), z.null()])),
  atualizado_em: z.optional(z.union([z.iso.datetime(), z.null()])),
})

/**
 * GetEquipeUsuarios
 */
export const zGetEquipeUsuarios = z.object({
  usuario_id: z.optional(z.union([z.uuid(), z.null()])),
  equipe_id: z.optional(z.union([z.uuid(), z.null()])),
  id: z.uuid(),
  criado_em: z.optional(z.union([z.iso.datetime(), z.null()])),
  atualizado_em: z.optional(z.union([z.iso.datetime(), z.null()])),
  equipes: z.optional(
    z.union([zAppSchemaEquipeUsuariosSchemaGetEquipes, z.null()])
  ),
  usuarios: z.optional(
    z.union([zAppSchemaEquipeUsuariosSchemaGetUsuarios, z.null()])
  ),
})

/**
 * GetUsuarios
 */
export const zAppSchemaUsuariosSchemaGetUsuariosOutput = z.object({
  nome_usuario: z.optional(z.string()),
  nome_completo: z.optional(z.union([z.string(), z.null()])),
  nivel: z.optional(z.union([z.string(), z.null()])),
  telefone: z.optional(z.union([z.string(), z.null()])),
  email: z.optional(z.string()),
  ativo: z.optional(z.boolean()),
  papel: z.optional(z.union([z.string(), z.null()])),
  papel_id: z.optional(z.union([z.uuid(), z.null()])),
  empresa_id: z.optional(z.union([z.uuid(), z.null()])),
  id: z.optional(z.uuid()),
  criado_em: z.optional(z.iso.datetime()),
  atualizado_em: z.optional(z.union([z.iso.datetime(), z.null()])),
  empresa: z.optional(z.union([zGetEmpresas, z.null()])),
  papeis: z.optional(z.union([zGetPapeis, z.null()])),
  usuarios_funcionalidades: z.optional(
    z.array(z.union([zGetUsuariosFuncionalidades, z.null()]))
  ),
  equipe_usuarios: z.optional(z.array(z.union([zGetEquipeUsuarios, z.null()]))),
})

/**
 * GetEquipes
 */
export const zAppSchemaEquipesSchemaGetEquipesOutput = z.object({
  nome: z.optional(z.union([z.string(), z.null()])),
  descricao: z.optional(z.union([z.string(), z.null()])),
  usuario_id: z.optional(z.union([z.uuid(), z.null()])),
  status: z.optional(z.union([z.boolean(), z.null()])),
  id: z.optional(z.uuid()),
  criado_em: z.optional(z.union([z.iso.datetime(), z.null()])),
  atualizado_em: z.optional(z.union([z.iso.datetime(), z.null()])),
  usuarios: z.optional(
    z.union([zAppSchemaUsuariosSchemaGetUsuariosOutput, z.null()])
  ),
  equipe_usuarios: z.optional(z.array(z.union([zGetEquipeUsuarios, z.null()]))),
})

/**
 * SortOp
 */
export const zAppSchemaEmpresasSchemaSortOp = z.enum(['ASC', 'DESC'])

/**
 * CursorDirection
 */
export const zAppSchemaEmpresasSchemaCursorDirection = z.enum(['next', 'prev'])

/**
 * UsuariosInclude
 */
export const zUsuariosInclude = z.enum([
  'nome_usuario',
  'nome_completo',
  'nivel',
  'telefone',
  'email',
  'ativo',
  'papel',
  'papel_id',
  'empresa_id',
  'id',
  'criado_em',
  'atualizado_em',
])

/**
 * UsuariosFuncionalidadesInclude
 */
export const zUsuariosFuncionalidadesInclude = z.enum([
  'usuario_id',
  'funcionalidade_id',
  'id',
  'criado_em',
  'atualizado_em',
])

/**
 * UsuariosFuncionalidadesExpand
 */
export const zUsuariosFuncionalidadesExpand = z.enum([
  'funcionalidades',
  'usuarios',
])

/**
 * UsuariosExpand
 */
export const zUsuariosExpand = z.enum([
  'empresas',
  'papeis',
  'usuarios_funcionalidades',
  'equipe_usuarios',
  'atendimentos',
  'equipes',
  'templates',
])

/**
 * TranscriptionCallback
 */
export const zTranscriptionCallback = z.object({
  job_id: z.optional(z.union([z.string(), z.null()])),
  tenant_id: z.optional(z.union([z.string(), z.null()])),
  atendimento_id: z.optional(z.union([z.string(), z.null()])),
  transcription: z.string(),
  status: z.string(),
  error: z.optional(z.union([z.string(), z.null()])),
})

/**
 * TemplatesInclude
 */
export const zTemplatesInclude = z.enum([
  'usuarios_id',
  'equipe_id',
  'nome',
  'descricao',
  'conteudo',
  'tags',
  'tipo',
  'id',
  'criado_em',
  'atualizado_em',
])

/**
 * ResponseLoginSessionToken
 */
export const zResponseLoginSessionToken = z.object({
  user: zAppSchemaUsuariosSchemaGetUsuariosOutput,
})

/**
 * ResponseLoginAcessToken
 */
export const zResponseLoginAcessToken = z.object({
  access_token: z.string(),
  token_type: z.string(),
  permission: z.union([z.array(z.string()), z.null()]),
  user: zAppSchemaUsuariosSchemaGetUsuariosOutput,
  papel: z.string(),
})

/**
 * ResponseEsqueciSenhaCodigo
 */
export const zResponseEsqueciSenhaCodigo = z.object({
  token: z.string(),
})

/**
 * ResponseEsqueciSenha
 */
export const zResponseEsqueciSenha = z.object({
  token: z.string(),
})

/**
 * RelatorioCallback
 */
export const zRelatorioCallback = z.object({
  task_id: z.string(),
  tenant_id: z.optional(z.union([z.string(), z.null()])),
  resultado: z.record(z.string(), z.unknown()),
  processado_em: z.number(),
})

/**
 * PostUsuariosFuncionalidades
 */
export const zPostUsuariosFuncionalidades = z.object({
  usuario_id: z.uuid(),
  funcionalidade_id: z.uuid(),
})

/**
 * PostUsuarios
 */
export const zPostUsuarios = z.object({
  nome_usuario: z.string(),
  nome_completo: z.optional(z.union([z.string(), z.null()])),
  nivel: z.optional(z.union([z.string(), z.null()])),
  telefone: z.optional(z.union([z.string(), z.null()])),
  email: z.string(),
  senha: z.string(),
  ativo: z.optional(z.boolean()).default(true),
  papel: z.optional(z.union([z.string(), z.null()])),
  papel_id: z.optional(z.union([z.uuid(), z.null()])),
  empresa_id: z.optional(z.union([z.uuid(), z.null()])),
})

/**
 * PostTemplates
 */
export const zPostTemplates = z.object({
  usuarios_id: z.uuid(),
  equipe_id: z.optional(z.union([z.uuid(), z.null()])),
  nome: z.string(),
  descricao: z.optional(z.union([z.string(), z.null()])),
  conteudo: z.string(),
  tags: z.optional(z.union([z.string(), z.null()])),
  tipo: z.optional(z.union([z.string(), z.null()])),
})

/**
 * PostPlanos
 */
export const zPostPlanos = z.object({
  nome: z.string(),
  descricao: z.optional(z.union([z.string(), z.null()])),
  preco: z.number(),
  ativo: z.optional(z.boolean()).default(true),
  max_usuarios: z.optional(z.int()).default(20),
  max_analises: z.optional(z.int()).default(100),
  recursos: z.optional(z.union([z.record(z.string(), z.unknown()), z.null()])),
})

/**
 * PostPapeisFuncionalidades
 */
export const zPostPapeisFuncionalidades = z.object({
  papel_id: z.uuid(),
  funcionalidade_id: z.uuid(),
})

/**
 * PostPapeis
 */
export const zPostPapeis = z.object({
  nome: z.string(),
  ativo: z.optional(z.boolean()).default(true),
  descricao: z.optional(z.union([z.string(), z.null()])),
})

/**
 * PostFuncionalidades
 */
export const zPostFuncionalidades = z.object({
  nome: z.string(),
  escopo: z.string(),
  caminho: z.string(),
  metodo: z.string(),
  descricao: z.optional(z.union([z.string(), z.null()])),
  categoria: z.optional(z.union([z.string(), z.null()])),
  sensivel: z.optional(z.union([z.boolean(), z.null()])),
  versao: z.optional(z.union([z.int(), z.null()])),
})

/**
 * PostEquipes
 */
export const zPostEquipes = z.object({
  nome: z.optional(z.union([z.string(), z.null()])),
  descricao: z.optional(z.union([z.string(), z.null()])),
  usuario_id: z.optional(z.union([z.uuid(), z.null()])),
  status: z.optional(z.union([z.boolean(), z.null()])),
})

/**
 * PostEquipeUsuarios
 */
export const zPostEquipeUsuarios = z.object({
  usuario_id: z.uuid(),
  equipe_id: z.uuid(),
})

/**
 * PostEmpresas
 */
export const zPostEmpresas = z.object({
  nome: z.string(),
  senha_admin: z.string(),
  usuario_admin: z.string(),
  nome_fantasia: z.optional(z.union([z.string(), z.null()])),
  cnpj: z.optional(z.union([z.string(), z.null()])),
  segmento: z.optional(z.union([z.string(), z.null()])),
  email: z.optional(z.union([z.string(), z.null()])),
  telefone: z.optional(z.union([z.string(), z.null()])),
  celular: z.optional(z.union([z.string(), z.null()])),
  cep: z.optional(z.union([z.string(), z.null()])),
  endereco: z.optional(z.union([z.string(), z.null()])),
  numero: z.optional(z.union([z.string(), z.null()])),
  complemento: z.optional(z.union([z.string(), z.null()])),
  bairro: z.optional(z.union([z.string(), z.null()])),
  cidade: z.optional(z.union([z.string(), z.null()])),
  estado: z.optional(z.union([z.string(), z.null()])),
  ativo: z.optional(z.boolean()).default(true),
  data_ativacao: z.optional(z.union([z.iso.datetime(), z.null()])),
  data_desativacao: z.optional(z.union([z.iso.datetime(), z.null()])),
  dominio: z.optional(z.union([z.string(), z.null()])),
  subdominio: z.optional(z.union([z.string(), z.null()])),
  plano_id: z.uuid(),
  plano_nome: z.optional(z.union([z.string(), z.null()])),
  valor_contrato: z.optional(z.union([z.number(), z.null()])),
  ciclo_cobranca: z.optional(z.string()).default('MENSAL'),
  max_usuarios: z.optional(z.int()).default(20),
  max_analises: z.optional(z.int()).default(100),
  configuracao: z.optional(
    z.union([z.record(z.string(), z.unknown()), z.null()])
  ),
})

/**
 * PostAtendimentos
 */
export const zPostAtendimentos = z.object({
  id: z.optional(z.union([z.uuid(), z.string(), z.null()])),
  nome_atendente: z.optional(z.union([z.string(), z.null()])),
  usuario_id: z.optional(z.union([z.uuid(), z.string(), z.null()])),
  status: z.optional(z.union([z.string(), z.null()])),
  total_chunks: z.optional(z.union([z.int(), z.null()])),
  file_format: z.optional(z.union([z.string(), z.null()])),
  filename: z.optional(z.union([z.string(), z.string(), z.null()])),
  relatorio: z.optional(z.union([z.record(z.string(), z.unknown()), z.null()])),
  transcricao: z.optional(z.union([z.string(), z.null()])),
})

/**
 * PlanosInclude
 */
export const zPlanosInclude = z.enum([
  'nome',
  'descricao',
  'preco',
  'ativo',
  'max_usuarios',
  'max_analises',
  'recursos',
  'id',
  'criado_em',
  'atualizado_em',
])

/**
 * PatchUsuariosFuncionalidades
 */
export const zPatchUsuariosFuncionalidades = z.object({
  usuario_id: z.optional(z.union([z.uuid(), z.null()])),
  funcionalidade_id: z.optional(z.union([z.uuid(), z.null()])),
})

/**
 * PatchUsuarios
 */
export const zPatchUsuarios = z.object({
  nome_usuario: z.optional(z.union([z.string(), z.null()])),
  nome_completo: z.optional(z.union([z.string(), z.null()])),
  nivel: z.optional(z.union([z.string(), z.null()])),
  telefone: z.optional(z.union([z.string(), z.null()])),
  email: z.optional(z.union([z.string(), z.null()])),
  senha: z.optional(z.union([z.string(), z.null()])),
  ativo: z.optional(z.union([z.boolean(), z.null()])),
  papel: z.optional(z.union([z.string(), z.null()])),
  papel_id: z.optional(z.union([z.uuid(), z.null()])),
  empresa_id: z.optional(z.union([z.uuid(), z.null()])),
})

/**
 * PatchTemplates
 */
export const zPatchTemplates = z.object({
  usuarios_id: z.optional(z.union([z.uuid(), z.null()])),
  equipe_id: z.optional(z.union([z.uuid(), z.null()])),
  nome: z.optional(z.union([z.string(), z.null()])),
  descricao: z.optional(z.union([z.string(), z.null()])),
  conteudo: z.optional(z.union([z.string(), z.null()])),
  tags: z.optional(z.union([z.string(), z.null()])),
  tipo: z.optional(z.union([z.string(), z.null()])),
})

/**
 * PatchPlanos
 */
export const zPatchPlanos = z.object({
  nome: z.optional(z.union([z.string(), z.null()])),
  descricao: z.optional(z.union([z.string(), z.null()])),
  preco: z.optional(z.union([z.number(), z.null()])),
  ativo: z.optional(z.union([z.boolean(), z.null()])),
  max_usuarios: z.optional(z.union([z.int(), z.null()])),
  max_analises: z.optional(z.union([z.int(), z.null()])),
  recursos: z.optional(z.union([z.record(z.string(), z.unknown()), z.null()])),
})

/**
 * PatchPapeisFuncionalidades
 */
export const zPatchPapeisFuncionalidades = z.object({
  papel_id: z.optional(z.union([z.uuid(), z.null()])),
  funcionalidade_id: z.optional(z.union([z.uuid(), z.null()])),
})

/**
 * PatchPapeis
 */
export const zPatchPapeis = z.object({
  nome: z.optional(z.union([z.string(), z.null()])),
  ativo: z.optional(z.union([z.boolean(), z.null()])),
  descricao: z.optional(z.union([z.string(), z.null()])),
})

/**
 * PatchFuncionalidades
 */
export const zPatchFuncionalidades = z.object({
  nome: z.optional(z.union([z.string(), z.null()])),
  escopo: z.optional(z.union([z.string(), z.null()])),
  caminho: z.optional(z.union([z.string(), z.null()])),
  metodo: z.optional(z.union([z.string(), z.null()])),
  descricao: z.optional(z.union([z.string(), z.null()])),
  categoria: z.optional(z.union([z.string(), z.null()])),
  sensivel: z.optional(z.union([z.boolean(), z.null()])),
  versao: z.optional(z.union([z.int(), z.null()])),
})

/**
 * PatchEquipes
 */
export const zPatchEquipes = z.object({
  nome: z.optional(z.union([z.string(), z.null()])),
  descricao: z.optional(z.union([z.string(), z.null()])),
  usuario_id: z.optional(z.union([z.uuid(), z.null()])),
  status: z.optional(z.union([z.boolean(), z.null()])),
})

/**
 * PatchEquipeUsuarios
 */
export const zPatchEquipeUsuarios = z.object({
  usuario_id: z.optional(z.union([z.uuid(), z.null()])),
  equipe_id: z.optional(z.union([z.uuid(), z.null()])),
})

/**
 * PatchEmpresas
 */
export const zPatchEmpresas = z.object({
  nome: z.optional(z.union([z.string(), z.null()])),
  nome_fantasia: z.optional(z.union([z.string(), z.null()])),
  cnpj: z.optional(z.union([z.string(), z.null()])),
  segmento: z.optional(z.union([z.string(), z.null()])),
  email: z.optional(z.union([z.string(), z.null()])),
  telefone: z.optional(z.union([z.string(), z.null()])),
  celular: z.optional(z.union([z.string(), z.null()])),
  cep: z.optional(z.union([z.string(), z.null()])),
  endereco: z.optional(z.union([z.string(), z.null()])),
  numero: z.optional(z.union([z.string(), z.null()])),
  complemento: z.optional(z.union([z.string(), z.null()])),
  bairro: z.optional(z.union([z.string(), z.null()])),
  cidade: z.optional(z.union([z.string(), z.null()])),
  estado: z.optional(z.union([z.string(), z.null()])),
  ativo: z.optional(z.union([z.boolean(), z.null()])),
  data_ativacao: z.optional(z.union([z.iso.datetime(), z.null()])),
  data_desativacao: z.optional(z.union([z.iso.datetime(), z.null()])),
  dominio: z.optional(z.union([z.string(), z.null()])),
  subdominio: z.optional(z.union([z.string(), z.null()])),
  plano_id: z.optional(z.union([z.uuid(), z.null()])),
  plano_nome: z.optional(z.union([z.string(), z.null()])),
  valor_contrato: z.optional(z.union([z.number(), z.null()])),
  ciclo_cobranca: z.optional(z.union([z.string(), z.null()])),
  max_usuarios: z.optional(z.union([z.int(), z.null()])),
  max_analises: z.optional(z.union([z.int(), z.null()])),
  configuracao: z.optional(
    z.union([z.record(z.string(), z.unknown()), z.null()])
  ),
})

/**
 * PatchAtendimentos
 */
export const zPatchAtendimentos = z.object({
  usuario_id: z.optional(z.union([z.uuid(), z.null()])),
  status: z.optional(z.union([z.string(), z.null()])),
  total_chunks: z.optional(z.union([z.int(), z.null()])),
  file_format: z.optional(z.union([z.string(), z.null()])),
  filename: z.optional(z.union([z.string(), z.null()])),
  relatorio: z.optional(z.union([z.record(z.string(), z.unknown()), z.null()])),
  transcricao: z.optional(z.union([z.string(), z.null()])),
})

/**
 * PapeisInclude
 */
export const zPapeisInclude = z.enum([
  'nome',
  'ativo',
  'descricao',
  'id',
  'criado_em',
  'atualizado_em',
])

/**
 * PapeisFuncionalidadesInclude
 */
export const zPapeisFuncionalidadesInclude = z.enum([
  'papel_id',
  'funcionalidade_id',
  'id',
  'criado_em',
  'atualizado_em',
])

/**
 * PapeisFuncionalidadesExpand
 */
export const zPapeisFuncionalidadesExpand = z.enum([
  'funcionalidades',
  'papeis',
])

/**
 * NovaSenha
 */
export const zNovaSenha = z.object({
  senha: z.string(),
})

/**
 * Meta
 * Metadados para operações
 */
export const zMeta = z.object({
  total_items: z.optional(z.int()).default(0),
  total_query: z.optional(z.int()).default(0),
  items_per_page: z.optional(z.union([z.int(), z.null()])),
  current_page: z.optional(z.union([z.int(), z.null()])),
  total_pages: z.optional(z.union([z.int(), z.null()])),
  next_cursor: z.optional(z.union([z.string(), z.null()])),
  prev_cursor: z.optional(z.union([z.string(), z.null()])),
  next_offset: z.optional(z.union([z.int(), z.null()])),
  prev_offset: z.optional(z.union([z.int(), z.null()])),
  has_next: z.optional(z.union([z.boolean(), z.null()])),
  has_prev: z.optional(z.union([z.boolean(), z.null()])),
})

/**
 * GetTenantEmpresas
 */
export const zGetTenantEmpresas = z.object({
  id: z.optional(z.uuid()),
  nome: z.optional(z.string()),
  nome_fantasia: z.optional(z.union([z.string(), z.null()])),
  dominio: z.optional(z.union([z.string(), z.null()])),
  subdominio: z.optional(z.union([z.string(), z.null()])),
  configuracao: z.optional(
    z.union([z.record(z.string(), z.unknown()), z.null()])
  ),
})

/**
 * GetTemplates
 */
export const zGetTemplates = z.object({
  usuarios_id: z.optional(z.uuid()),
  equipe_id: z.optional(z.union([z.uuid(), z.null()])),
  nome: z.optional(z.string()),
  descricao: z.optional(z.union([z.string(), z.null()])),
  conteudo: z.optional(z.string()),
  tags: z.optional(z.union([z.string(), z.null()])),
  tipo: z.optional(z.union([z.string(), z.null()])),
  id: z.optional(z.uuid()),
  criado_em: z.optional(z.iso.datetime()),
  atualizado_em: z.optional(z.union([z.iso.datetime(), z.null()])),
})

/**
 * GetPapeisFuncionalidades
 */
export const zGetPapeisFuncionalidades = z.object({
  papel_id: z.optional(z.union([z.uuid(), z.null()])),
  funcionalidade_id: z.optional(z.union([z.uuid(), z.null()])),
  id: z.optional(z.uuid()),
  criado_em: z.optional(z.union([z.iso.datetime(), z.null()])),
  atualizado_em: z.optional(z.union([z.iso.datetime(), z.null()])),
  funcionalidades: z.optional(z.union([zGetFuncionalidades, z.null()])),
  papeis: z.optional(z.union([zGetPapeis, z.null()])),
})

/**
 * GetLinkUsuarios
 */
export const zGetLinkUsuarios = z.object({
  token: z.string(),
})

/**
 * GetAtendimentos
 */
export const zGetAtendimentos = z.object({
  usuario_id: z.optional(z.union([z.uuid(), z.null()])),
  nome_atendente: z.optional(z.union([z.string(), z.null()])),
  status: z.optional(z.union([z.string(), z.null()])),
  total_chunks: z.optional(z.union([z.int(), z.null()])),
  file_format: z.optional(z.union([z.string(), z.null()])),
  filename: z.optional(z.union([z.string(), z.null()])),
  relatorio: z.optional(z.union([z.record(z.string(), z.unknown()), z.null()])),
  transcricao: z.optional(z.union([z.string(), z.null()])),
  id: z.uuid(),
  criado_em: z.optional(z.union([z.iso.datetime(), z.null()])),
  atualizado_em: z.optional(z.union([z.iso.datetime(), z.null()])),
  usuarios: z.optional(
    z.union([zAppSchemaUsuariosSchemaGetUsuariosOutput, z.null()])
  ),
})

/**
 * FuncionalidadesInclude
 */
export const zFuncionalidadesInclude = z.enum([
  'chave',
  'nome',
  'escopo',
  'caminho',
  'metodo',
  'descricao',
  'categoria',
  'sensivel',
  'versao',
  'id',
  'criado_em',
  'atualizado_em',
])

/**
 * FileType
 */
export const zFileType = z.enum([
  'application',
  'image',
  'text',
  'video',
  'audio',
])

/**
 * EsqueciSenha
 */
export const zEsqueciSenha = z.object({
  email: z.string(),
})

/**
 * Detail
 */
export const zDetail = z.object({
  loc: z.optional(z.union([z.array(z.union([z.string(), z.int()])), z.null()])),
  msg: z.string(),
  type: z.optional(z.union([z.string(), z.null()])),
  debug: z.optional(z.union([z.string(), z.null()])),
})

/**
 * ErrorSchema
 */
export const zErrorSchema = z.object({
  detail: z.array(zDetail),
})

/**
 * EquipesInclude
 */
export const zEquipesInclude = z.enum([
  'nome',
  'descricao',
  'usuario_id',
  'status',
  'id',
  'criado_em',
  'atualizado_em',
])

/**
 * EquipesExpand
 */
export const zEquipesExpand = z.enum(['usuarios', 'equipe_usuarios'])

/**
 * EquipeUsuariosInclude
 */
export const zEquipeUsuariosInclude = z.enum([
  'usuario_id',
  'equipe_id',
  'id',
  'criado_em',
  'atualizado_em',
])

/**
 * EquipeUsuariosExpand
 */
export const zEquipeUsuariosExpand = z.enum(['equipes', 'usuarios'])

/**
 * EmpresasInclude
 */
export const zEmpresasInclude = z.enum([
  'nome',
  'nome_fantasia',
  'cnpj',
  'segmento',
  'email',
  'telefone',
  'celular',
  'cep',
  'endereco',
  'numero',
  'complemento',
  'bairro',
  'cidade',
  'estado',
  'ativo',
  'data_ativacao',
  'data_desativacao',
  'dominio',
  'subdominio',
  'plano_id',
  'plano_nome',
  'valor_contrato',
  'ciclo_cobranca',
  'max_usuarios',
  'max_analises',
  'configuracao',
  'id',
  'criado_em',
  'atualizado_em',
])

/**
 * EmpresasExpand
 */
export const zEmpresasExpand = z.enum(['planos'])

/**
 * Body_start_recording
 */
export const zBodyStartRecording = z.object({
  type_data: z.optional(zFileType),
})

/**
 * Body_login_session_token
 */
export const zBodyLoginSessionToken = z.object({
  username: z.string(),
  password: z.string(),
})

/**
 * Body_login_access_token
 */
export const zBodyLoginAccessToken = z.object({
  username: z.string(),
  password: z.string(),
})

/**
 * Body_finish_recording
 */
export const zBodyFinishRecording = z.object({
  filename: z.string(),
  atendimento_id: z.string(),
})

/**
 * Body_finalizar_atendimentos_chunk
 */
export const zBodyFinalizarAtendimentosChunk = z.object({
  forcar_reprocessamento: z.optional(z.boolean()).default(false),
})

/**
 * Body_criar_atendimentos_v2
 */
export const zBodyCriarAtendimentosV2 = z.object({
  id: z.optional(z.union([z.uuid(), z.string(), z.null()])),
  nome_atendente: z.optional(z.union([z.string(), z.null()])),
  usuario_id: z.optional(z.union([z.uuid(), z.string(), z.null()])),
  status: z.optional(z.union([z.string(), z.null()])),
  total_chunks: z.optional(z.union([z.int(), z.null()])),
  file_format: z.optional(z.union([z.string(), z.null()])),
  filename: z.optional(z.union([z.string(), z.null()])),
  transcricao: z.optional(z.union([z.string(), z.null()])),
})

/**
 * Body_criar_atendimentos_chunk
 */
export const zBodyCriarAtendimentosChunk = z.object({
  id: z.optional(z.union([z.uuid(), z.string(), z.null()])),
  nome_atendente: z.optional(z.union([z.string(), z.null()])),
  usuario_id: z.optional(z.union([z.uuid(), z.string(), z.null()])),
  status: z.optional(z.union([z.string(), z.null()])),
  total_chunks: z.optional(z.union([z.int(), z.null()])),
  file_format: z.optional(z.union([z.string(), z.null()])),
  filename: z.optional(z.union([z.string(), z.null()])),
  transcricao: z.optional(z.union([z.string(), z.null()])),
})

/**
 * Body_create_file_file__post
 */
export const zBodyCreateFileFilePost = z.object({
  file: z.string(),
  type_data: zFileType,
})

/**
 * Body_append_chunk
 */
export const zBodyAppendChunk = z.object({
  chunk: z.string(),
  filename: z.string(),
})

/**
 * AtendimentosInclude
 */
export const zAtendimentosInclude = z.enum([
  'usuario_id',
  'status',
  'nome_atendente',
  'filename',
  'transcricao',
  'id',
  'criado_em',
  'atualizado_em',
])

/**
 * AtendimentosExpand
 */
export const zAtendimentosExpand = z.enum(['usuarios'])

/**
 * ApiSuccess[NoneType]
 */
export const zApiSuccessNoneType = z.object({
  msg: z.optional(z.union([z.string(), z.null()])),
  meta: z.optional(z.union([zMeta, z.null()])),
  data: z.optional(z.union([z.array(z.null()), z.null()])),
})

/**
 * ApiSuccess[GetUsuarios]
 */
export const zApiSuccessGetUsuarios = z.object({
  msg: z.optional(z.union([z.string(), z.null()])),
  meta: z.optional(z.union([zMeta, z.null()])),
  data: z.optional(
    z.union([z.array(zAppSchemaUsuariosSchemaGetUsuariosOutput), z.null()])
  ),
})

/**
 * ApiSuccess[GetUsuariosFuncionalidades]
 */
export const zApiSuccessGetUsuariosFuncionalidades = z.object({
  msg: z.optional(z.union([z.string(), z.null()])),
  meta: z.optional(z.union([zMeta, z.null()])),
  data: z.optional(z.union([z.array(zGetUsuariosFuncionalidades), z.null()])),
})

/**
 * ApiSuccess[GetTenantEmpresas]
 */
export const zApiSuccessGetTenantEmpresas = z.object({
  msg: z.optional(z.union([z.string(), z.null()])),
  meta: z.optional(z.union([zMeta, z.null()])),
  data: z.optional(z.union([z.array(zGetTenantEmpresas), z.null()])),
})

/**
 * ApiSuccess[GetTemplates]
 */
export const zApiSuccessGetTemplates = z.object({
  msg: z.optional(z.union([z.string(), z.null()])),
  meta: z.optional(z.union([zMeta, z.null()])),
  data: z.optional(z.union([z.array(zGetTemplates), z.null()])),
})

/**
 * ApiSuccess[GetPlanos]
 */
export const zApiSuccessGetPlanos = z.object({
  msg: z.optional(z.union([z.string(), z.null()])),
  meta: z.optional(z.union([zMeta, z.null()])),
  data: z.optional(z.union([z.array(zGetPlanos), z.null()])),
})

/**
 * ApiSuccess[GetPapeis]
 */
export const zApiSuccessGetPapeis = z.object({
  msg: z.optional(z.union([z.string(), z.null()])),
  meta: z.optional(z.union([zMeta, z.null()])),
  data: z.optional(z.union([z.array(zGetPapeis), z.null()])),
})

/**
 * ApiSuccess[GetPapeisFuncionalidades]
 */
export const zApiSuccessGetPapeisFuncionalidades = z.object({
  msg: z.optional(z.union([z.string(), z.null()])),
  meta: z.optional(z.union([zMeta, z.null()])),
  data: z.optional(z.union([z.array(zGetPapeisFuncionalidades), z.null()])),
})

/**
 * ApiSuccess[GetFuncionalidades]
 */
export const zApiSuccessGetFuncionalidades = z.object({
  msg: z.optional(z.union([z.string(), z.null()])),
  meta: z.optional(z.union([zMeta, z.null()])),
  data: z.optional(z.union([z.array(zGetFuncionalidades), z.null()])),
})

/**
 * ApiSuccess[GetEquipes]
 */
export const zApiSuccessGetEquipes = z.object({
  msg: z.optional(z.union([z.string(), z.null()])),
  meta: z.optional(z.union([zMeta, z.null()])),
  data: z.optional(
    z.union([z.array(zAppSchemaEquipesSchemaGetEquipesOutput), z.null()])
  ),
})

/**
 * ApiSuccess[GetEquipeUsuarios]
 */
export const zApiSuccessGetEquipeUsuarios = z.object({
  msg: z.optional(z.union([z.string(), z.null()])),
  meta: z.optional(z.union([zMeta, z.null()])),
  data: z.optional(z.union([z.array(zGetEquipeUsuarios), z.null()])),
})

/**
 * ApiSuccess[GetEmpresas]
 */
export const zApiSuccessGetEmpresas = z.object({
  msg: z.optional(z.union([z.string(), z.null()])),
  meta: z.optional(z.union([zMeta, z.null()])),
  data: z.optional(z.union([z.array(zGetEmpresas), z.null()])),
})

/**
 * ApiSuccess[GetAtendimentos]
 */
export const zApiSuccessGetAtendimentos = z.object({
  msg: z.optional(z.union([z.string(), z.null()])),
  meta: z.optional(z.union([zMeta, z.null()])),
  data: z.optional(z.union([z.array(zGetAtendimentos), z.null()])),
})

export const zListTenantsTenantsGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

export const zRemoveTenantTenantsTenantIdDeleteData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    tenant_id: z.string(),
  }),
  query: z.optional(z.never()),
})

export const zLerAtendimentosData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      all_data: z.optional(z.boolean()).default(true),
      nome_atendente: z.optional(z.union([z.string(), z.null()])),
      usuario_id: z.optional(z.union([z.string(), z.null()])),
      status: z.optional(z.union([z.string(), z.null()])),
      filename: z.optional(z.union([z.string(), z.null()])),
      transcricao: z.optional(z.union([z.string(), z.null()])),
      id: z.optional(z.union([z.string(), z.null()])),
      criado_em: z.optional(z.union([z.string(), z.null()])),
      atualizado_em: z.optional(z.union([z.string(), z.null()])),
      limit: z.optional(z.union([z.int(), z.null()])),
      offset: z.optional(z.union([z.int(), z.null()])),
      cursor: z.optional(z.union([z.string(), z.null()])),
      cursor_field: z.optional(zAtendimentosInclude),
      cursor_direction: z.optional(zAppSchemaEmpresasSchemaCursorDirection),
      include: z.optional(z.array(zAtendimentosInclude)).default([]),
      exclude: z.optional(z.array(zAtendimentosInclude)).default([]),
      expand: z.optional(z.union([z.array(zAtendimentosExpand), z.null()])),
      count_only: z.optional(z.boolean()).default(false),
      distinct: z.optional(z.boolean()).default(false),
      sort_op: z.optional(zAppSchemaEmpresasSchemaSortOp),
      sort_field: z.optional(zAtendimentosInclude),
    })
  ),
})

/**
 * Successful Response
 */
export const zLerAtendimentosResponse = zApiSuccessGetAtendimentos

export const zCriarAtendimentosData = z.object({
  body: zPostAtendimentos,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zCriarAtendimentosResponse = zGetAtendimentos

export const zProcessarAudioData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      all_data: z.optional(z.boolean()).default(true),
      nome_atendente: z.optional(z.union([z.string(), z.null()])),
      usuario_id: z.optional(z.union([z.string(), z.null()])),
      status: z.optional(z.union([z.string(), z.null()])),
      filename: z.optional(z.union([z.string(), z.null()])),
      transcricao: z.optional(z.union([z.string(), z.null()])),
      id: z.optional(z.union([z.string(), z.null()])),
      criado_em: z.optional(z.union([z.string(), z.null()])),
      atualizado_em: z.optional(z.union([z.string(), z.null()])),
      limit: z.optional(z.union([z.int(), z.null()])),
      offset: z.optional(z.union([z.int(), z.null()])),
      cursor: z.optional(z.union([z.string(), z.null()])),
      cursor_field: z.optional(zAtendimentosInclude),
      cursor_direction: z.optional(zAppSchemaEmpresasSchemaCursorDirection),
      include: z.optional(z.array(zAtendimentosInclude)).default([]),
      exclude: z.optional(z.array(zAtendimentosInclude)).default([]),
      expand: z.optional(z.union([z.array(zAtendimentosExpand), z.null()])),
      count_only: z.optional(z.boolean()).default(false),
      distinct: z.optional(z.boolean()).default(false),
      sort_op: z.optional(zAppSchemaEmpresasSchemaSortOp),
      sort_field: z.optional(zAtendimentosInclude),
    })
  ),
})

export const zRemoverAtendimentosData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zRemoverAtendimentosResponse = zApiSuccessNoneType

export const zAtualizarAtendimentosData = z.object({
  body: zPatchAtendimentos,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zAtualizarAtendimentosResponse = zApiSuccessNoneType

export const zCriarAtendimentosV2Data = z.object({
  body: z.optional(zBodyCriarAtendimentosV2),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zCriarAtendimentosV2Response = zGetAtendimentos

export const zCriarAtendimentosChunkData = z.object({
  body: z.optional(zBodyCriarAtendimentosChunk),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zCriarAtendimentosChunkResponse = zGetAtendimentos

export const zFinalizarAtendimentosChunkData = z.object({
  body: z.optional(zBodyFinalizarAtendimentosChunk),
  path: z.optional(z.never()),
  query: z.object({
    atendimento_id: z.string(),
  }),
})

/**
 * Successful Response
 */
export const zFinalizarAtendimentosChunkResponse = zGetAtendimentos

export const zLerFuncionalidadesData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      all_data: z.optional(z.boolean()).default(true),
      chave: z.optional(z.union([z.string(), z.null()])),
      nome: z.optional(z.union([z.string(), z.null()])),
      escopo: z.optional(z.union([z.string(), z.null()])),
      caminho: z.optional(z.union([z.string(), z.null()])),
      metodo: z.optional(z.union([z.string(), z.null()])),
      descricao: z.optional(z.union([z.string(), z.null()])),
      categoria: z.optional(z.union([z.string(), z.null()])),
      sensivel: z.optional(z.union([z.string(), z.null()])),
      versao: z.optional(z.union([z.string(), z.null()])),
      id: z.optional(z.union([z.string(), z.null()])),
      criado_em: z.optional(z.union([z.string(), z.null()])),
      atualizado_em: z.optional(z.union([z.string(), z.null()])),
      limit: z.optional(z.union([z.int(), z.null()])),
      offset: z.optional(z.union([z.int(), z.null()])),
      cursor: z.optional(z.union([z.string(), z.null()])),
      cursor_field: z.optional(zFuncionalidadesInclude),
      cursor_direction: z.optional(zAppSchemaEmpresasSchemaCursorDirection),
      include: z.optional(z.array(zFuncionalidadesInclude)).default([]),
      exclude: z.optional(z.array(zFuncionalidadesInclude)).default([]),
      count_only: z.optional(z.boolean()).default(false),
      distinct: z.optional(z.boolean()).default(false),
      sort_op: z.optional(zAppSchemaEmpresasSchemaSortOp),
      sort_field: z.optional(zFuncionalidadesInclude),
    })
  ),
})

/**
 * Successful Response
 */
export const zLerFuncionalidadesResponse = zApiSuccessGetFuncionalidades

export const zCriarFuncionalidadesData = z.object({
  body: zPostFuncionalidades,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zCriarFuncionalidadesResponse = zApiSuccessNoneType

export const zRemoverFuncionalidadesData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zRemoverFuncionalidadesResponse = zApiSuccessNoneType

export const zAtualizarFuncionalidadesData = z.object({
  body: zPatchFuncionalidades,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zAtualizarFuncionalidadesResponse = zApiSuccessNoneType

export const zCreateFileFilePostData = z.object({
  body: zBodyCreateFileFilePost,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Response Create File File  Post
 * Successful Response
 */
export const zCreateFileFilePostResponse = z.string()

export const zStartRecordingData = z.object({
  body: z.optional(zBodyStartRecording),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Response Start Recording
 * Successful Response
 */
export const zStartRecordingResponse = z.record(z.string(), z.unknown())

export const zAppendChunkData = z.object({
  body: zBodyAppendChunk,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Response Append Chunk
 * Successful Response
 */
export const zAppendChunkResponse = z.record(z.string(), z.unknown())

export const zGetFileByFilenameFileFilenameGetData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    filename: z.string(),
  }),
  query: z.optional(z.never()),
})

export const zGetMinioFileUrlByFilenameFileMinioFileUrlFilenameGetData =
  z.object({
    body: z.optional(z.never()),
    path: z.object({
      filename: z.string(),
    }),
    query: z.optional(z.never()),
  })

export const zDownloadFileFileDownloadFilenameGetData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    filename: z.string(),
  }),
  query: z.optional(z.never()),
})

export const zDownloadFileFileDownloadFilenameGet2Data = z.object({
  body: z.optional(z.never()),
  path: z.object({
    filename: z.string(),
  }),
  query: z.optional(z.never()),
})

export const zListAllFilesFileFilesListGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Response List All Files File Files List  Get
 * Successful Response
 */
export const zListAllFilesFileFilesListGetResponse = z.array(z.string())

export const zLerUsuariosData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      all_data: z.optional(z.boolean()).default(true),
      nome_usuario: z.optional(z.union([z.string(), z.null()])),
      nome_completo: z.optional(z.union([z.string(), z.null()])),
      nivel: z.optional(z.union([z.string(), z.null()])),
      telefone: z.optional(z.union([z.string(), z.null()])),
      email: z.optional(z.union([z.string(), z.null()])),
      ativo: z.optional(z.union([z.string(), z.null()])),
      papel: z.optional(z.union([z.string(), z.null()])),
      papel_id: z.optional(z.union([z.string(), z.null()])),
      empresa_id: z.optional(z.union([z.string(), z.null()])),
      id: z.optional(z.union([z.string(), z.null()])),
      criado_em: z.optional(z.union([z.string(), z.null()])),
      atualizado_em: z.optional(z.union([z.string(), z.null()])),
      limit: z.optional(z.union([z.int(), z.null()])),
      offset: z.optional(z.union([z.int(), z.null()])),
      cursor: z.optional(z.union([z.string(), z.null()])),
      cursor_field: z.optional(zUsuariosInclude),
      cursor_direction: z.optional(zAppSchemaEmpresasSchemaCursorDirection),
      include: z.optional(z.array(zUsuariosInclude)).default([]),
      exclude: z.optional(z.array(zUsuariosInclude)).default([]),
      expand: z.optional(z.union([z.array(zUsuariosExpand), z.null()])),
      count_only: z.optional(z.boolean()).default(false),
      distinct: z.optional(z.boolean()).default(false),
      sort_op: z.optional(zAppSchemaEmpresasSchemaSortOp),
      sort_field: z.optional(zUsuariosInclude),
    })
  ),
})

/**
 * Successful Response
 */
export const zLerUsuariosResponse = zApiSuccessGetUsuarios

export const zCriarUsuariosData = z.object({
  body: zPostUsuarios,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zCriarUsuariosResponse = zApiSuccessNoneType

export const zRemoverUsuariosData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zRemoverUsuariosResponse = zApiSuccessNoneType

export const zAtualizarUsuariosData = z.object({
  body: zPatchUsuarios,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zAtualizarUsuariosResponse = zApiSuccessNoneType

export const zLinkUsuariosData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.object({
    papel_id: z.string(),
    token_expiration: z.int(),
  }),
})

/**
 * Successful Response
 */
export const zLinkUsuariosResponse = zGetLinkUsuarios

export const zCriarUsuariosLinkData = z.object({
  body: zPostUsuarios,
  path: z.object({
    token: z.string(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zCriarUsuariosLinkResponse = zApiSuccessNoneType

export const zLerUsuariosFuncionalidadesData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      all_data: z.optional(z.boolean()).default(true),
      usuario_id: z.optional(z.union([z.string(), z.null()])),
      funcionalidade_id: z.optional(z.union([z.string(), z.null()])),
      id: z.optional(z.union([z.string(), z.null()])),
      criado_em: z.optional(z.union([z.string(), z.null()])),
      atualizado_em: z.optional(z.union([z.string(), z.null()])),
      limit: z.optional(z.union([z.int(), z.null()])),
      offset: z.optional(z.union([z.int(), z.null()])),
      cursor: z.optional(z.union([z.string(), z.null()])),
      cursor_field: z.optional(zUsuariosFuncionalidadesInclude),
      cursor_direction: z.optional(zAppSchemaEmpresasSchemaCursorDirection),
      include: z.optional(z.array(zUsuariosFuncionalidadesInclude)).default([]),
      exclude: z.optional(z.array(zUsuariosFuncionalidadesInclude)).default([]),
      expand: z.optional(
        z.union([z.array(zUsuariosFuncionalidadesExpand), z.null()])
      ),
      count_only: z.optional(z.boolean()).default(false),
      distinct: z.optional(z.boolean()).default(false),
      sort_op: z.optional(zAppSchemaEmpresasSchemaSortOp),
      sort_field: z.optional(zUsuariosFuncionalidadesInclude),
    })
  ),
})

/**
 * Successful Response
 */
export const zLerUsuariosFuncionalidadesResponse =
  zApiSuccessGetUsuariosFuncionalidades

export const zCriarUsuariosFuncionalidadesData = z.object({
  body: zPostUsuariosFuncionalidades,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zCriarUsuariosFuncionalidadesResponse = zApiSuccessNoneType

export const zRemoverUsuariosFuncionalidadesData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zRemoverUsuariosFuncionalidadesResponse = zApiSuccessNoneType

export const zAtualizarUsuariosFuncionalidadesData = z.object({
  body: zPatchUsuariosFuncionalidades,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zAtualizarUsuariosFuncionalidadesResponse = zApiSuccessNoneType

export const zFinishRecordingData = z.object({
  body: zBodyFinishRecording,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Response Finish Recording
 * Successful Response
 */
export const zFinishRecordingResponse = z.record(z.string(), z.unknown())

export const zLerPapeisData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      all_data: z.optional(z.boolean()).default(true),
      nome: z.optional(z.union([z.string(), z.null()])),
      ativo: z.optional(z.union([z.string(), z.null()])),
      descricao: z.optional(z.union([z.string(), z.null()])),
      id: z.optional(z.union([z.string(), z.null()])),
      criado_em: z.optional(z.union([z.string(), z.null()])),
      atualizado_em: z.optional(z.union([z.string(), z.null()])),
      limit: z.optional(z.union([z.int(), z.null()])),
      offset: z.optional(z.union([z.int(), z.null()])),
      cursor: z.optional(z.union([z.string(), z.null()])),
      cursor_field: z.optional(zPapeisInclude),
      cursor_direction: z.optional(zAppSchemaEmpresasSchemaCursorDirection),
      include: z.optional(z.array(zPapeisInclude)).default([]),
      exclude: z.optional(z.array(zPapeisInclude)).default([]),
      count_only: z.optional(z.boolean()).default(false),
      distinct: z.optional(z.boolean()).default(false),
      sort_op: z.optional(zAppSchemaEmpresasSchemaSortOp),
      sort_field: z.optional(zPapeisInclude),
    })
  ),
})

/**
 * Successful Response
 */
export const zLerPapeisResponse = zApiSuccessGetPapeis

export const zCriarPapeisData = z.object({
  body: zPostPapeis,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zCriarPapeisResponse = zApiSuccessNoneType

export const zRemoverPapeisData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zRemoverPapeisResponse = zApiSuccessNoneType

export const zAtualizarPapeisData = z.object({
  body: zPatchPapeis,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zAtualizarPapeisResponse = zApiSuccessNoneType

export const zLoginAccessTokenData = z.object({
  body: zBodyLoginAccessToken,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zLoginAccessTokenResponse = zResponseLoginAcessToken

export const zLoginSessionTokenData = z.object({
  body: zBodyLoginSessionToken,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zLoginSessionTokenResponse = zResponseLoginSessionToken

export const zEsqueciSenhaData = z.object({
  body: zEsqueciSenha,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zEsqueciSenhaResponse = zResponseEsqueciSenha

export const zEsqueciSenhaCodigoData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.object({
    code: z.string(),
  }),
  headers: z.object({
    Authentication: z.string(),
  }),
})

/**
 * Successful Response
 */
export const zEsqueciSenhaCodigoResponse = zResponseEsqueciSenhaCodigo

export const zNovaSenhaData = z.object({
  body: zNovaSenha,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
  headers: z.object({
    Authentication: z.string(),
  }),
})

export const zLerPlanosData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      all_data: z.optional(z.boolean()).default(true),
      nome: z.optional(z.union([z.string(), z.null()])),
      descricao: z.optional(z.union([z.string(), z.null()])),
      preco: z.optional(z.union([z.string(), z.null()])),
      ativo: z.optional(z.union([z.string(), z.null()])),
      max_usuarios: z.optional(z.union([z.string(), z.null()])),
      max_analises: z.optional(z.union([z.string(), z.null()])),
      recursos: z.optional(z.union([z.string(), z.null()])),
      id: z.optional(z.union([z.string(), z.null()])),
      criado_em: z.optional(z.union([z.string(), z.null()])),
      atualizado_em: z.optional(z.union([z.string(), z.null()])),
      limit: z.optional(z.union([z.int(), z.null()])),
      offset: z.optional(z.union([z.int(), z.null()])),
      cursor: z.optional(z.union([z.string(), z.null()])),
      cursor_field: z.optional(zPlanosInclude),
      cursor_direction: z.optional(zAppSchemaEmpresasSchemaCursorDirection),
      include: z.optional(z.array(zPlanosInclude)).default([]),
      exclude: z.optional(z.array(zPlanosInclude)).default([]),
      count_only: z.optional(z.boolean()).default(false),
      distinct: z.optional(z.boolean()).default(false),
      sort_op: z.optional(zAppSchemaEmpresasSchemaSortOp),
      sort_field: z.optional(zPlanosInclude),
    })
  ),
})

/**
 * Successful Response
 */
export const zLerPlanosResponse = zApiSuccessGetPlanos

export const zCriarPlanosData = z.object({
  body: zPostPlanos,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zCriarPlanosResponse = zApiSuccessNoneType

export const zRemoverPlanosData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zRemoverPlanosResponse = zApiSuccessNoneType

export const zAtualizarPlanosData = z.object({
  body: zPatchPlanos,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zAtualizarPlanosResponse = zApiSuccessNoneType

export const zLerPapeisFuncionalidadesData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      all_data: z.optional(z.boolean()).default(true),
      papel_id: z.optional(z.union([z.string(), z.null()])),
      funcionalidade_id: z.optional(z.union([z.string(), z.null()])),
      id: z.optional(z.union([z.string(), z.null()])),
      criado_em: z.optional(z.union([z.string(), z.null()])),
      atualizado_em: z.optional(z.union([z.string(), z.null()])),
      limit: z.optional(z.union([z.int(), z.null()])),
      offset: z.optional(z.union([z.int(), z.null()])),
      cursor: z.optional(z.union([z.string(), z.null()])),
      cursor_field: z.optional(zPapeisFuncionalidadesInclude),
      cursor_direction: z.optional(zAppSchemaEmpresasSchemaCursorDirection),
      include: z.optional(z.array(zPapeisFuncionalidadesInclude)).default([]),
      exclude: z.optional(z.array(zPapeisFuncionalidadesInclude)).default([]),
      expand: z.optional(
        z.union([z.array(zPapeisFuncionalidadesExpand), z.null()])
      ),
      count_only: z.optional(z.boolean()).default(false),
      distinct: z.optional(z.boolean()).default(false),
      sort_op: z.optional(zAppSchemaEmpresasSchemaSortOp),
      sort_field: z.optional(zPapeisFuncionalidadesInclude),
    })
  ),
})

/**
 * Successful Response
 */
export const zLerPapeisFuncionalidadesResponse =
  zApiSuccessGetPapeisFuncionalidades

export const zCriarPapeisFuncionalidadesData = z.object({
  body: zPostPapeisFuncionalidades,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zCriarPapeisFuncionalidadesResponse = zApiSuccessNoneType

export const zRemoverPapeisFuncionalidadesData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zRemoverPapeisFuncionalidadesResponse = zApiSuccessNoneType

export const zAtualizarPapeisFuncionalidadesData = z.object({
  body: zPatchPapeisFuncionalidades,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zAtualizarPapeisFuncionalidadesResponse = zApiSuccessNoneType

export const zLerEquipesData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      all_data: z.optional(z.boolean()).default(true),
      nome: z.optional(z.union([z.string(), z.null()])),
      descricao: z.optional(z.union([z.string(), z.null()])),
      usuario_id: z.optional(z.union([z.string(), z.null()])),
      status: z.optional(z.union([z.string(), z.null()])),
      id: z.optional(z.union([z.string(), z.null()])),
      criado_em: z.optional(z.union([z.string(), z.null()])),
      atualizado_em: z.optional(z.union([z.string(), z.null()])),
      limit: z.optional(z.union([z.int(), z.null()])),
      offset: z.optional(z.union([z.int(), z.null()])),
      cursor: z.optional(z.union([z.string(), z.null()])),
      cursor_field: z.optional(zEquipesInclude),
      cursor_direction: z.optional(zAppSchemaEmpresasSchemaCursorDirection),
      include: z.optional(z.array(zEquipesInclude)).default([]),
      exclude: z.optional(z.array(zEquipesInclude)).default([]),
      expand: z.optional(z.union([z.array(zEquipesExpand), z.null()])),
      count_only: z.optional(z.boolean()).default(false),
      distinct: z.optional(z.boolean()).default(false),
      sort_op: z.optional(zAppSchemaEmpresasSchemaSortOp),
      sort_field: z.optional(zEquipesInclude),
    })
  ),
})

/**
 * Successful Response
 */
export const zLerEquipesResponse = zApiSuccessGetEquipes

export const zCriarEquipesData = z.object({
  body: zPostEquipes,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zCriarEquipesResponse = zApiSuccessNoneType

export const zRemoverEquipesData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zRemoverEquipesResponse = zApiSuccessNoneType

export const zAtualizarEquipesData = z.object({
  body: zPatchEquipes,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zAtualizarEquipesResponse = zApiSuccessNoneType

export const zLerEquipeUsuariosData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      all_data: z.optional(z.boolean()).default(true),
      usuario_id: z.optional(z.union([z.string(), z.null()])),
      equipe_id: z.optional(z.union([z.string(), z.null()])),
      id: z.optional(z.union([z.string(), z.null()])),
      criado_em: z.optional(z.union([z.string(), z.null()])),
      atualizado_em: z.optional(z.union([z.string(), z.null()])),
      limit: z.optional(z.union([z.int(), z.null()])),
      offset: z.optional(z.union([z.int(), z.null()])),
      cursor: z.optional(z.union([z.string(), z.null()])),
      cursor_field: z.optional(zEquipeUsuariosInclude),
      cursor_direction: z.optional(zAppSchemaEmpresasSchemaCursorDirection),
      include: z.optional(z.array(zEquipeUsuariosInclude)).default([]),
      exclude: z.optional(z.array(zEquipeUsuariosInclude)).default([]),
      expand: z.optional(z.union([z.array(zEquipeUsuariosExpand), z.null()])),
      count_only: z.optional(z.boolean()).default(false),
      distinct: z.optional(z.boolean()).default(false),
      sort_op: z.optional(zAppSchemaEmpresasSchemaSortOp),
      sort_field: z.optional(zEquipeUsuariosInclude),
    })
  ),
})

/**
 * Successful Response
 */
export const zLerEquipeUsuariosResponse = zApiSuccessGetEquipeUsuarios

export const zCriarEquipeUsuariosData = z.object({
  body: zPostEquipeUsuarios,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zCriarEquipeUsuariosResponse = zApiSuccessNoneType

export const zRemoverEquipeUsuariosData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zRemoverEquipeUsuariosResponse = zApiSuccessNoneType

export const zAtualizarEquipeUsuariosData = z.object({
  body: zPatchEquipeUsuarios,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zAtualizarEquipeUsuariosResponse = zApiSuccessNoneType

export const zLerTemplatesData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      all_data: z.optional(z.boolean()).default(true),
      usuarios_id: z.optional(z.union([z.string(), z.null()])),
      equipe_id: z.optional(z.union([z.string(), z.null()])),
      nome: z.optional(z.union([z.string(), z.null()])),
      descricao: z.optional(z.union([z.string(), z.null()])),
      conteudo: z.optional(z.union([z.string(), z.null()])),
      tags: z.optional(z.union([z.string(), z.null()])),
      tipo: z.optional(z.union([z.string(), z.null()])),
      id: z.optional(z.union([z.string(), z.null()])),
      criado_em: z.optional(z.union([z.string(), z.null()])),
      atualizado_em: z.optional(z.union([z.string(), z.null()])),
      limit: z.optional(z.union([z.int(), z.null()])),
      offset: z.optional(z.union([z.int(), z.null()])),
      cursor: z.optional(z.union([z.string(), z.null()])),
      cursor_field: z.optional(zTemplatesInclude),
      cursor_direction: z.optional(zAppSchemaEmpresasSchemaCursorDirection),
      include: z.optional(z.array(zTemplatesInclude)).default([]),
      exclude: z.optional(z.array(zTemplatesInclude)).default([]),
      count_only: z.optional(z.boolean()).default(false),
      distinct: z.optional(z.boolean()).default(false),
      sort_op: z.optional(zAppSchemaEmpresasSchemaSortOp),
      sort_field: z.optional(zTemplatesInclude),
    })
  ),
})

/**
 * Successful Response
 */
export const zLerTemplatesResponse = zApiSuccessGetTemplates

export const zCriarTemplatesData = z.object({
  body: zPostTemplates,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zCriarTemplatesResponse = zApiSuccessNoneType

export const zRemoverTemplatesData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zRemoverTemplatesResponse = zApiSuccessNoneType

export const zAtualizarTemplatesData = z.object({
  body: zPatchTemplates,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zAtualizarTemplatesResponse = zApiSuccessNoneType

export const zLerEmpresasData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      all_data: z.optional(z.boolean()).default(true),
      nome: z.optional(z.union([z.string(), z.null()])),
      nome_fantasia: z.optional(z.union([z.string(), z.null()])),
      cnpj: z.optional(z.union([z.string(), z.null()])),
      segmento: z.optional(z.union([z.string(), z.null()])),
      email: z.optional(z.union([z.string(), z.null()])),
      telefone: z.optional(z.union([z.string(), z.null()])),
      celular: z.optional(z.union([z.string(), z.null()])),
      cep: z.optional(z.union([z.string(), z.null()])),
      endereco: z.optional(z.union([z.string(), z.null()])),
      numero: z.optional(z.union([z.string(), z.null()])),
      complemento: z.optional(z.union([z.string(), z.null()])),
      bairro: z.optional(z.union([z.string(), z.null()])),
      cidade: z.optional(z.union([z.string(), z.null()])),
      estado: z.optional(z.union([z.string(), z.null()])),
      ativo: z.optional(z.union([z.string(), z.null()])),
      data_ativacao: z.optional(z.union([z.string(), z.null()])),
      data_desativacao: z.optional(z.union([z.string(), z.null()])),
      dominio: z.optional(z.union([z.string(), z.null()])),
      subdominio: z.optional(z.union([z.string(), z.null()])),
      plano_id: z.optional(z.union([z.string(), z.null()])),
      plano_nome: z.optional(z.union([z.string(), z.null()])),
      valor_contrato: z.optional(z.union([z.string(), z.null()])),
      ciclo_cobranca: z.optional(z.union([z.string(), z.null()])),
      max_usuarios: z.optional(z.union([z.string(), z.null()])),
      max_analises: z.optional(z.union([z.string(), z.null()])),
      configuracao: z.optional(z.union([z.string(), z.null()])),
      id: z.optional(z.union([z.string(), z.null()])),
      criado_em: z.optional(z.union([z.string(), z.null()])),
      atualizado_em: z.optional(z.union([z.string(), z.null()])),
      limit: z.optional(z.union([z.int(), z.null()])),
      offset: z.optional(z.union([z.int(), z.null()])),
      cursor: z.optional(z.union([z.string(), z.null()])),
      cursor_field: z.optional(zEmpresasInclude),
      cursor_direction: z.optional(zAppSchemaEmpresasSchemaCursorDirection),
      include: z.optional(z.array(zEmpresasInclude)).default([]),
      exclude: z.optional(z.array(zEmpresasInclude)).default([]),
      expand: z.optional(z.union([z.array(zEmpresasExpand), z.null()])),
      count_only: z.optional(z.boolean()).default(false),
      distinct: z.optional(z.boolean()).default(false),
      sort_op: z.optional(zAppSchemaEmpresasSchemaSortOp),
      sort_field: z.optional(zEmpresasInclude),
    })
  ),
})

/**
 * Successful Response
 */
export const zLerEmpresasResponse = zApiSuccessGetEmpresas

export const zCriarEmpresasData = z.object({
  body: zPostEmpresas,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zCriarEmpresasResponse = zApiSuccessNoneType

export const zLerEmpresasTenantData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      all_data: z.optional(z.boolean()).default(true),
      id: z.optional(z.union([z.string(), z.null()])),
      nome: z.optional(z.union([z.string(), z.null()])),
      dominio: z.optional(z.union([z.string(), z.null()])),
      subdominio: z.optional(z.union([z.string(), z.null()])),
      configuracao: z.optional(z.union([z.string(), z.null()])),
      limit: z.optional(z.union([z.int(), z.null()])),
      offset: z.optional(z.union([z.int(), z.null()])),
    })
  ),
})

/**
 * Successful Response
 */
export const zLerEmpresasTenantResponse = zApiSuccessGetTenantEmpresas

export const zRemoverEmpresasData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zRemoverEmpresasResponse = zApiSuccessNoneType

export const zAtualizarEmpresasData = z.object({
  body: zPatchEmpresas,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zAtualizarEmpresasResponse = zApiSuccessNoneType

export const zUpdateTranscriptionWebhookTranscriptionPatchData = z.object({
  body: zTranscriptionCallback,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

export const zUpdateRelatorioWebhookRelatorioPatchData = z.object({
  body: zRelatorioCallback,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})
